### ISSUE TITLE
Websocket restart doesn't work after 60 sec.

### ISSUE THREAD

**Issue by e-techniker** [gotify/android#101]
Hi,

i am using Gotify Server 2.0.13.
On my Android 7.1.1 Phone i have installed the Gotify App 2.0.10.

If the websocket connection was broken, i see in the log: "WebSocket: scheduling a restart in 60 second(s)."
But this does not work immediately. (see screenshot) Only if I open the Gotify App, or turn wifi off and on then websocket will restart in the next few seconds. 

Battery optimizations are disabled.

This problem occurs with direct connection to the Gotify Server or via Proxy (nginx or apache)

What can i do so that the websocket restart works after 60 seconds?

Direct connection tho Gotify Server:
![direct](https://user-images.githubusercontent.com/61084849/74589048-3c4c2000-5002-11ea-8188-4d20d84c5554.jpg)

Connection via Proxy (apache, nginx)
![via proxy](https://user-images.githubusercontent.com/61084849/74589053-42420100-5002-11ea-83cb-079e8245f143.jpg)

**Comment by jmattheis** [comment]
Is the foreground notification still present when this error occurs?

**Comment by e-techniker** [comment]
Yes, the foreground notification is always present.
![foreground](https://user-images.githubusercontent.com/61084849/74673502-9807dc00-51af-11ea-905f-1c7ade668084.JPG)

**Comment by jmattheis** [comment]
I've just tested this feature, and it seems to work well for me. Could you try to manually trigger the websocket error by killing gotify while the android app is connected and then restarting gotify and checking if the app reconnects? 

Are you sure you've disable battery optimization? Could you make a screenshot of the app settings?

**Comment by e-techniker** [comment]
I've restarted the gotify server, but the websocket doesn't restart after 60 seconds.
After about 30 minutes I opened the gotify app manually, then the websocket restarted:

![photo_2020-02-17_19-09-06](https://user-images.githubusercontent.com/61084849/74677656-3cdae700-51b9-11ea-9b69-5b2074540d55.jpg)


The battery optimization for the gotify app is disabled:
![apps](https://user-images.githubusercontent.com/61084849/74677688-53813e00-51b9-11ea-8a74-2f29841281c5.jpg)

**Comment by jmattheis** [comment]
Hmm weird. I cannot reproduce it sadly. I'll have a look at the code later but at first glance I couldn't find the error. 

Have you tried the steps in https://github.com/gotify/android/issues/101#issuecomment-587092321 with an open app or closed app? In case it was not open could you try this too?

**Comment by e-techniker** [comment]
I've tried the steps with an open and a closed app. But the error occurs in both cases.

**Comment by jmattheis** [comment]
But you do receive notifications when you send a message and the connection is not broken?

**Comment by e-techniker** [comment]
Yes, if the websocket connection ist not broken, then i receive push notifications.

**Comment by jmattheis** [comment]
Okay, seems like a bug on the app side. I'll have a look at the code later.

**Comment by e-techniker** [comment]
This problem often occurs, when my Smartphone roams between my two WLAN Access Points.
I can also reproduce it, when i restart the gotify server.

**Comment by jmattheis** [comment]
Hey there, I had another look at the code today, I think I found the problem (tho I still can't reproduce it). I've pushed my fix to https://github.com/gotify/android/compare/fix-reconnect-maybe 

Could you try it out and verify that the problem is fixed? Here the debug build of the branch, if you don't want to build it yourself: [gotify-debug-fix-reconnect.zip](https://github.com/gotify/android/files/4706211/gotify-debug-fix-reconnect.zip)

**Comment by e-techniker** [comment]
Many thanks. I will test it and give you feedback.

**Comment by e-techniker** [comment]
I got a new error, when switching between cellular network and wlan:

![websocket](https://user-images.githubusercontent.com/61084849/83737325-1c914400-a653-11ea-97bc-3963bdf1cc9a.PNG)

The websocket doesn't restart automatically. I have to click on the reload button in the Gotify App to restart the websocket.

**Comment by jmattheis** [comment]
Yeah, this seems like a different problem. Currently, the android app expects that the user was logged out if the websocket was closed. This could also be caused by a read/write timeout. I'll fix this, when I find time for it. In the meantime I will merge the reconnect fix.

**Comment by e-techniker** [comment]
Thanks. But why does the websocket close the connection when roaming (a few hundred milliseconds) between my wifi access points?

**Comment by jmattheis** [comment]
Could you have a look at the log of gotify/server? My guess it, that there is a read/write timeout, but I'm not sure.

**Comment by e-techniker** [comment]
After roaming between the access points, i got the following error in the Gotify server log:

WebSocket: ReadError websocket: close 1006 (abnormal closure): unexpected EOF
WebSocket: ReadError websocket: close 1006 (abnormal closure): unexpected EOF

[GIN] 2020/06/13 - 11:49:52 | 200 |     777.904µs |    xxx.xxx.xxx.xxx | GET      "/stream?token=xxxxx"
[GIN] 2020/06/13 - 11:49:52 | 200 |     715.664µs |    xxx.xxx.xxx.xxx | GET      "/stream?token=xxxxx"
[GIN] 2020/06/13 - 11:49:52 | 200 |    2.092032ms |    xxx.xxx.xxx.xxx | GET      "/message?limit=10"
[GIN] 2020/06/13 - 11:49:52 | 200 |    1.934221ms |    xxx.xxx.xxx.xxx | GET      "/message?limit=10"

In the Gotify app log i got this:

![websocket_app](https://user-images.githubusercontent.com/61084849/84565885-d0d64d00-ad6c-11ea-96a1-aeb882d8f347.png)

I seems, that there are two open websockets from the same client?

**Comment by jmattheis** [comment]
This is not the client closed error in the foreground notification or?

**Comment by e-techniker** [comment]
In the foreground notification i got this error:

![websocket_foreground](https://user-images.githubusercontent.com/61084849/84567160-113ac880-ad77-11ea-8e12-c144ccec0e9d.PNG)

**Comment by jmattheis** [comment]
yeah, this is perfectly fine, the connection will get broken when you switch between access points.

**Comment by e-techniker** [comment]
But the connection breaks only at the Gotify app. Other apps, for example pushover, whatsapp or telegram works instantly after switch between access points.

**Comment by jmattheis** [comment]
I don't know how these apps work internally, but the error that is logged inside gotify is pretty low level.
Gotify can't prevent this error, we can reduce the reconnect timeout, to try again after a couple seconds, but the connection will fail regardless. Maybe these apps just don't notify you.

The websocket service does indeed run twice, this is a bug. But is most likely difficult to debug.

**Comment by e-techniker** [comment]
Problem solved. I bought a new Smartphone (Samsung Galaxy M31) with Android 10.
I have no more  broken websockets after switchting between my sccess points.

So, i think that was a problem with my Android 7 phone.
