### ISSUE TITLE
Hope adding customized notification method and repeat option

### ISSUE THREAD

**Issue by 93pBc** [gotify/android#109]
Hi,

It's a very great suite you have made, thanks for the work!

I'm trying to make it working with zabbix to replace PagerDuty, as an alert system, so if i can change the default notification sound with a customized one, like a much longer one (like a phone call notification sound) than the default message sound, would be more likely to wake me up successfully during night. With repeat option would be better.

Thanks for your time.

**Comment by jmattheis** [comment]
If you have a recent version of android, you can change the notification sound inside the android notification settings.
![sound](https://user-images.githubusercontent.com/14895212/81386132-0baceb80-9104-11ea-93e5-ca352e1d5923.gif)

**Comment by 93pBc** [comment]
Ah, thanks for the demonstration.
I checked my phone, although it's based on Android 8.1, but it's running a deeply customized OS named Smartisan OS, which many settings are missing or changed compare to a pure google android os, like many other android phones in China. 
What a pity. However, many thanks for your time and this great work!
