### ISSUE TITLE
Username and password in image url

### ISSUE THREAD

**Issue by Colgaton** [gotify/android#111]
When using markdown and sending something like below, it does not render it:

` ![Camera Image](https://user:pass@domain.com/abc/test.jpg)`

First I thought it would be an android limitation, but it works fine in Chrome. Any idea?

**Comment by jmattheis** [comment]
Looks like the library gotify uses for markdown support on android, doesn't support this by default.

**Comment by cyb3rko** [comment]
After some research I've learned that the user and password in the URL are converted to an "Authorization" header.  
With an OkHttp interceptor we could let the image loading library convert the username and password into an basic auth authorization header.

Is this issue still relevant?

**Comment by jmattheis** [comment]
I'd say yes, as the behavior between the gotify in the browser and android shouldn't differ.
