### ISSUE TITLE
[feature request] full screen (or large) popup

### ISSUE THREAD

**Issue by wsw70** [gotify/android#120]
I am not sure if this is not limited by Android, but it would be awesome to have the ability to get full-screen or large pop-ups for some messages.

There may be several use cases, for me it is to ensure that my home users (namely children) get a visible notification if some of the messages are sent to them.

It could also be useful for some critical alerts.

**Comment by jmattheis** [comment]
Seems like a good addition. A high-priority notification could be used. https://developer.android.com/training/notify-user/time-sensitive

**Comment by jmattheis** [comment]
Closing as not needed as there aren't many upvotes or comments from other users.
