### ISSUE TITLE
Android configuration for getting notification

### ISSUE THREAD

**Issue by mehdirouhandeh** [gotify/android#121]
Hi,
I'm an Android developer and want to know how can I configure our app to receive notification from Gotify.

**Comment by jmattheis** [comment]
Hi, you could copy our websocket service https://github.com/gotify/android/blob/master/app/src/main/java/com/github/gotify/service/WebSocketService.java and use it to receive messages in your app.

**Comment by mehdirouhandeh** [comment]
@jmattheis thank you for your help
