### ISSUE TITLE
Copy message contents to clipboard

### ISSUE THREAD

**Issue by jmattheis** [gotify/android#128]

**Comment by karmanyaahm** [comment]
This seems to have been resolved by @KROSF but there's no PR 😕?

**Comment by jmattheis** [comment]
Oops, closed now (:. https://github.com/gotify/android/pull/135

**Comment by linusboyle** [comment]
Sorry but I cannot copy the content now. There is no menu or popup or anything when I longpress the notification in the bar or in the app.
