### ISSUE TITLE
FeatureRequest: OpenHAB Action

### ISSUE THREAD

**Issue by quixony** [gotify/android#130]
I'd really like to use GOTIFY as an action in openhab2. There is already an action for PushOver but I was not able to get the sources of that addon to adjust it to match gotify. 
I was able to adjust the pushover files of PHPServerMonitor http://www.phpservermonitor.org/ (just /vendor/php-pushover/php-pushover/Pushover.php hast to be adjusted a bit). 

I am willing to test if any working example of an openhab addon is available.

**Comment by jmattheis** [comment]
I think this should be a feature request in openhab2, nothing can be done in gotify to support this.

**Comment by quixony** [comment]
I know that there is not much that can be done in the code of gotify. 
For gotify it would be another popular service where it is integrated. I already took a look at the bindings of openhab but my programming skill are limited. So I thought in here someone also might be interested and has the skills to programm a binding or refacture an existing one.
