### ISSUE TITLE
Disable notifications

### ISSUE THREAD

**Issue by info-droid** [gotify/android#132]
Hi,

Thanks for your awesome tool!

Could you please add an option to disable notifications?
As Gotify use a lot of battery, and i don't need it all the time, it's not convenient to logout / login each time.

Thanks!

**Comment by jmattheis** [comment]
You can force close gotify via android. This should stop the app completely.

**Comment by steevanb** [comment]
(Question was by me from another account)

Yes i know, but I think it will be a good add to your application, more practical than stop the application.

**Comment by jmattheis** [comment]
I think this isn't worth the developer effort, to disable the main feature of this application.

**Comment by cyb3rko** [comment]
Jannis, you decide.
So we can close this issue as well
