### ISSUE TITLE
Connection problem notifications remain even after the connection is restored

### ISSUE THREAD

**Issue by schneidersoft** [gotify/android#141]
I'm using gotify/android v2.0.13 gotify/server v2.0.20

I installed the server from binaries and use nginx infront with the setting from https://gotify.net/docs/nginx

I turned mobile data off and left to have lunch :) I got lots of notifications while the connection was severed. 
When I was within range of the wifi again I manually checked the applications for new notifications and there were none. However, the android notifications pull down still showed "connection lost will retry in 20 minutes." Only after closing the app and opening it again did the notification change to "Listening to https://....."

Shortly after the notification changed again this time to "WebSocket closed; The client-token could be invalid", even though I was able to send notifications and recieve them on the android.
![Screenshot_20201018-182811](https://user-images.githubusercontent.com/7611333/96374063-62652980-1168-11eb-9d8a-ec6a13aa344a.png)
![Screenshot_20201018-182828](https://user-images.githubusercontent.com/7611333/96374068-63965680-1168-11eb-93d9-1c726a7f57ce.png)

**Comment by schneidersoft** [comment]
I should also note; Just opening the app causes notifications. One imediately when the app openes. This changes the status to "Listening to ..." and another shortly after which causes the gotify status to blink...

**Comment by jmattheis** [comment]
Please try out the newest version of the android app (2.0.14). For reducing the intrusiveness of the "listening ..." notification see https://github.com/gotify/android#minimize-the-gotify-foreground-notification
