### ISSUE TITLE
Feature Request: Option to hide Gotify listening notification..

### ISSUE THREAD

**Issue by nicholaswilde** [gotify/android#144]
Please add an option to hide the Gotify listening notification. Current, I can only hide it by the Android system settings but that hides all Gotify notifications.

**Comment by jmattheis** [comment]
You can minimize the notification as described in here https://github.com/gotify/android#minimize-the-gotify-foreground-notification
the notification is there to give the process a higher priority. This makes it less likely, that android stops the application.

**Comment by nicholaswilde** [comment]
Thanks. That worked.
