### ISSUE TITLE
Feature request: UI improvements

### ISSUE THREAD

**Issue by alekna** [gotify/android#145]
Hi,

I know that Gotify is pretty opinionated but I'll try my luck. I'm looking to switch from Pushover to Gotify as I prefer in-house hosted solutions for reliability and predictability. I thought Gotify will be a nice replacement for Pushover until I noticed certain UI differences that are show stoppers for me.

1. Would it be possible to display absolute time as its shown in Pushover? Displaying relative time makes absolutely no sense to me because you can't tell easily when exactly event happened.

2. I prefer seeing as many messages in a list without having to scroll. Pushover has implemented it quite nicely. Gotify message list seems to be quite bloated for me. It fits nearly 60% less of a messages compared to Pushover.

![image](https://user-images.githubusercontent.com/10272121/100290845-32355580-2f74-11eb-9a1d-7884422fa807.png)

**Comment by jmattheis** [comment]
Hi @alekna,

cool that you've tried out Gotify (:.

1. It is already possible to see the exact timestamp by pressing the on the time (see also https://github.com/gotify/android/issues/90).
   I think this is also usage depended / opinionated, some users prefer relative and some absolute time.
   As of this nature, this probably won't change. Also, this isn't a frequently discussed topic,
   so either users don't care or are okay with the current format.

2. Originally, Gotify had a similar format that was changed in https://github.com/gotify/android/pull/56 to support longer titles. The extra space is especially needed for smaller devices, as they normally display image, title, date & delete button in the same  I'd be ok with reducing the image size, but that probably won't change much.

**Comment by alekna** [comment]
Hi @jmattheis, thanks for your reply.

1. It would be nice if default #90 behavior was configurable in `Settings`. Can't imagine sane user whose preference is absolute time clicking on each notification. Sad to hear this won't change. If this software wasn't so much opinionated probably community would discuss topics like this more actively.

2. Now exactly sure how #56 improved support for longer titles as in Pushover I can fit more information before title gets wrapped and it doesn't come at an expense of message list size.

![image](https://user-images.githubusercontent.com/10272121/100391890-cf53c500-302c-11eb-8762-8226e8bf9e20.png)

**Comment by jmattheis** [comment]
Hey again,

1. I understand the reasoning and would be ok with adding such a setting.
2. Well because it should be possible to differentiate the title from the message, we made it bold and a little bigger. To still allow bigger titles the title was moved above the Message/Image. But yeah, I understand your argument.

**Comment by RemiRigal** [comment]
About the layout of the messages, what about having a setting to choose the size ? It could be as follow:
- Small: Display image as an inline icon with the title
- Medium: Same as the Pushover example
- Large: Same as it is now

**Comment by alekna** [comment]
@RemiRigal sounds good to me. Are you willing to implement it?

**Comment by RemiRigal** [comment]
I will probably have some time to do this in April. I would like to have @jmattheis approval or opinion first though, I don't want to spend time on something that won't be merged.

**Comment by jmattheis** [comment]
Sure, I'd be okay with different message layout settings. But I like to keep it simple, so how about two settings like "normal" and "compact"?

**Comment by alekna** [comment]
@RemiRigal how's your progress with this feature?

**Comment by cyb3rko** [comment]
@alekna @jmattheis I played around and implemented a compact message layout.
What do you think?

[BEFORE](https://user-images.githubusercontent.com/46033730/194730294-602b496f-7ad1-409c-8358-716613ade099.png)

[AFTER](https://user-images.githubusercontent.com/46033730/194730297-15d485f6-b201-4cab-81eb-34c58126af79.png)

And I think especially for the compact layout we don't really need the trash can as you can simply swipe the message to the left to delete it, right?

**Comment by jmattheis** [comment]
Looks great! I'm not sure if we should omit the trash icon, as it allows you to delete messages much faster than by swiping, but this could be changed later if that's a problem for some users.

**Comment by cyb3rko** [comment]
Okay, I'm going to prepare a pull request for this (and bring the trash icon to the compact layout as well).

**Comment by cyb3rko** [comment]
Compact message layout added in #246.
As both points @alekna mentioned are implemented, it's finally time to close this, right?

**Comment by alekna** [comment]
Correct, @cyb3rko. Thank you! :)

**Comment by cyb3rko** [comment]
Glad I could contribute.
I just found this repo and decided to implement this here, as it has been staling for 2 years now 😬
