### ISSUE TITLE
Markdown not rendered

### ISSUE THREAD

**Issue by neolium** [gotify/android#146]
![notify](https://user-images.githubusercontent.com/1325527/102981821-d675d200-4509-11eb-8d7d-42fb13d60d5b.png)
Hi guys, first thanks for this app/solution ;-)
Im using the following versions and code to send a markdown message. On the app it shows only the code, on the webui it is displayed correctly...
Gotify **Android**: v2.0.14
Gotify **Server**: 2.0.20
Android-**OS**:  10 (Samsung Galaxy S10+)
Example Code (**PHP**): https://paste.ee/p/bV3Os
What do i do wrong? i would like to implement actions but cant find a working example (clicking on the message works fine). Even the app seems not to be running in the background - even with disabled battery-save-options.

Thanks

so long
neo
Edit: Added Screenshot

**Comment by jmattheis** [comment]
Markdown isn't rendered in the notification only on the message overview. This works fine with your example:
![image](https://user-images.githubusercontent.com/14895212/102985697-8269ee00-4507-11eb-991b-a97f7c8fab54.png)

> i would like to implement actions but cant find a working example (clicking on the message works fine).

When clicking the notification gotify.net is opened. Other "actions" aren't implemented yet.

> Even the app seems not to be running in the background - even with disabled battery-save-options.

What do you mean exactly, do you not receive notifications after some time?

**Comment by neolium** [comment]
Hey Jannis, Thanks for your fast reply.Ah okay, if my phone "sleeps" some time (Gotify is excluded, WhatsApp is working as well and is excluded from hibernating). Here is the log: 2020-12-23T10:20:08.311Z INFO: WebSocket(13): opened2020-12-23T10:20:08.088Z INFO: WebSocket(13): starting...2020-12-23T10:20:08.088Z INFO: WebSocket(12): closing existing connection.2020-12-23T10:16:57.903Z INFO: WebSocket: scheduling a restart in 60 second(s) (via alarm manager)2020-12-23T10:16:57.884Z ERROR: WebSocket(12): failure  Message: java.net.SocketException: Software caused connection abort	at java.net.SocketInputStream.socketRead0(Native Method)	at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)	at java.net.SocketInputStream.read(SocketInputStream.java:176)	at java.net.SocketInputStream.read(SocketInputStream.java:144)	at okio.Okio$2.read(Okio.java:140)	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)	at okio.RealBufferedSource.request(RealBufferedSource.java:68)	at okio.RealBufferedSource.require(RealBufferedSource.java:61)	at okio.RealBufferedSource.readByte(RealBufferedSource.java:74)	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117)	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)	at java.lang.Thread.run(Thread.java:919)2020-12-23T09:56:23.070Z INFO: WebSocket(12): received message {"id":36,"appid":1,"message":"Foo *bar* ![](https://www.w3schools.com/images/w3schools_green.jpg)","title":"Test","priority":6,"extras":{"client::display":{"contentType":"text/markdown"},"client::notification":{"click":{"url":"https://gotify.net"}}},"date":"2020-12-23T09:56:24.496981339Z"}2020-12-23T09:56:16.721Z INFO: WebSocket(12): received message {"id":35,"appid":1,"message":"Foo *bar* ![](https://www.w3schools.com/images/w3schools_green.jpg)","title":"Test","priority":6,"extras":{"client::display":{"contentType":"text/markdown"},"client::notification":{"click":{"url":"https://gotify.net"}}},"date":"2020-12-23T09:56:18.202747221Z"}2020-12-23T09:56:12.601Z INFO: Entering LogsActivity2020-12-23T09:56:00.438Z INFO: WebSocket(12): received message {"id":34,"appid":1,"message":"Foo *bar* ![](https://www.w3schools.com/images/w3schools_green.jpg)","title":"Test","priority":6,"extras":{"client::display":{"contentType":"text/markdown"},"client::notification":{"click":{"url":"https://gotify.net"}}},"date":"2020-12-23T09:56:01.882145597Z"}2020-12-23T09:55:56.379Z INFO: Entering LogsActivity2020-12-23T09:55:51.891Z INFO: Loading more messages for -12020-12-23T09:55:51.878Z INFO: WebSocket(12): opened2020-12-23T09:55:51.877Z INFO: Entering MessagesActivity2020-12-23T09:55:51.832Z INFO: Server version: 2.0.20@2020-10-06-18:29:432020-12-23T09:55:51.763Z INFO: Network reconnected2020-12-23T09:55:51.756Z INFO: WebSocket(12): starting...2020-12-23T09:55:51.749Z INFO: Starting WebSocketService2020-12-23T09:55:51.749Z INFO: WebSocket(11): closing existing connection.2020-12-23T09:55:51.723Z INFO: Authenticated as neo2020-12-23T09:55:51.594Z INFO: Entering InitializationActivity2020-12-23T09:55:44.860Z INFO: Removing message with id 33Best regardsneo

**Comment by jmattheis** [comment]
Does gotify/server output anything? Do you use a reverse proxy?

**Comment by neolium** [comment]
No reverseproxy or anything like that. I tested something maybe it solves the issue. Then i add the solution here ))

**Comment by jmattheis** [comment]
If you haven't solved it yet, feel free to reopen the issue.

**Comment by Aerion** [comment]
Hi,

_As this is related to the original post of this issue I didn't open a new one._

Would it be feasible to render the markdown in the notification? Or is this an android limitation?
If it's feasible, I'd be interested in having the markdown rendered in the notification for some apps (the gotify term), as I'm the one designing the markdown content.

What do you think?

**Comment by jmattheis** [comment]
Ahh, you mean the markdown isn't rendered inside the push notification in android. The markdown should be stripped from the body as described in here https://github.com/gotify/android/issues/74
