### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [gotify/android#149]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by jmattheis** [comment]
Seems cool, I'd be happy if someone wants to contribute this to gotify/andorid (:.

**Comment by PanderMusubi** [comment]
An example can be found at https://github.com/y20k/transistor/tree/master/metadata
