### ISSUE TITLE
Feature request: mute "application" option in the gotify app

### ISSUE THREAD

**Issue by abeulich** [gotify/android#151]
Hi all, I came across gotify just yesterday and it's great. Love the simplicity and control! 

Now I've tried to implemement a selective notification mirroring from my Android phone to my Desktop using Tasker.
(Don't stop reading here, it's not a Tasker-related request ;)

I've managed to intercept the notifications and send their title and body as a message to the gotify server API.
They pop up on the Desktop.

The only issue is: they are coming back to my Android phone and create a duplicate notification there of course. 

It'd be great to be able to "mute"/unsubscribe from an application in the gotify app to prevent this circular reference 
and the duplicate notifications. What do you think about that?

If that's out of question, how could I achieve the same result? 
I think separate user accounts (w/ separate applications) for Desktop and phone could work, although that's quite clumsy.

Cheers and many thanks, Alex

**Comment by jmattheis** [comment]
Closing because of duplicate.
