### ISSUE TITLE
Feature Request: Option to start Gotify by booting the smartphone

### ISSUE THREAD

**Issue by hjboehle** [gotify/android#152]
Hello and thanks for your time to develop Gotify. Gotify is for me and my private homeautomation project very helpful. One feature for me is missing. When the smartphone starts, I want the Gotify app is starting automatically. This feature would perfect, when it is in the option of the app is selectable.

**Comment by jmattheis** [comment]
This should already be implemented see https://github.com/gotify/android/issues/25

**Comment by hjboehle** [comment]
Thanks for the quick answer. I don't have found the issue #25, sorry. I will check my configuration and afterwards I post the result.
