### ISSUE TITLE
On features

### ISSUE THREAD

**Issue by nabw** [gotify/android#154]
Hi everyone, 
This is not really an issue but I couldn't find any other way to contact you. I was wondering if it is possible to fully replace google push notification with gotify, as I recently installed Lineage OS and I require them for a banking app (I didn't know beforehand, silly me). 
Has anyone else tried this? 
Best, 
NB

**Comment by jmattheis** [comment]
Some features could be replaced with Gotify, but the android app (in your case the banking app) must support it and I'd guess no banking app supports Gotify (:.

**Comment by nabw** [comment]
I'm sorry to hear that, but thank you for the answer!
