### ISSUE TITLE
Killed every day same time

### ISSUE THREAD

**Issue by quthla** [gotify/android#155]
I was using 2.0.12 with no issues until a few days ago when I rebased on 2.0.14. Since then the websocket service dies about the same time and will run fine for the rest of the day.

There's nothing else but this in adb logs or Gotify logs unfortunately. 

![Screenshot_20210209-133235__01](https://user-images.githubusercontent.com/30180109/107400525-2cc2c280-6b02-11eb-8333-84e22d0e4ee9.jpg)
![Screenshot_20210207-104723__01](https://user-images.githubusercontent.com/30180109/107400534-2df3ef80-6b02-11eb-9fd7-6d488dc04f73.jpg)
![Screenshot_20210206-111054__01](https://user-images.githubusercontent.com/30180109/107400537-2e8c8600-6b02-11eb-9146-59cdc3241a1b.jpg)

I've also disabled any battery optimizations for Gotify and 2.0.12 went fine like forever without ever stopping.

**Comment by jmattheis** [comment]
could you add logs from gotify/server and from the log view inside the android app?

**Comment by quthla** [comment]
WebSocket: ReadError websocket: close 1006 (abnormal closure): unexpected EOF

This is from the server. No surprise as the websocket service is being terminated without being able to properly close the connection. In the app there's nothing in the logs. It'll just stop logging anything and continue only after launching the app again. 

I've installed the official 2.0.14 alongside my fork to make sure it's not related to any of my changes but the chances are quite low.

**Comment by jmattheis** [comment]
Do you need to manually restart the app, or does it reconnect by itself?

**Comment by quthla** [comment]
It is being force closed and thus will never reconnect unfortunately.

**Comment by jmattheis** [comment]
Hmm, gotify most likely won't stop itself via the activity manager, so android is killing the app. Do you receive message frequent in intervals?

**Comment by MnM001** [comment]
@quthla did you manage to solve the disconnect issue? noticed you have written in my thread but since you have removed the posts. Does that mean that is solved for you?

**Comment by quthla** [comment]
I've reinstalled my fork yesterday after I found out that the official Gotify app would not get killed every day just like my fork used to before the update. And what can I say, there's no issue anymore now.

Seems the Android system messed something up there.
