### ISSUE TITLE
Support for Firebase Cloud Messaging

### ISSUE THREAD

**Issue by AndreKR** [gotify/android#159]
Currently the Gotify Android app seems to use a notification to keep itself from being killed and also recommends to disable battery optimization in the README.

Both could be avoided by using [Firebase Cloud Messaging](https://firebase.google.com/docs/cloud-messaging).

There's no need to send any actual data via FCM, so there's no privacy concern. FCM would only be used to wake up to app and trigger a check for new messages.

Note that the [standard way](https://firebase.google.com/docs/cloud-messaging/android/client) of setting up FCM is to compile in the credentials, but this isn't required ([1](https://firebase.googleblog.com/2017/03/take-control-of-your-firebase-init-on.html), [2](https://firebase.google.com/docs/projects/multiprojects#use_multiple_projects_in_your_application), [3](https://stackoverflow.com/questions/39913573/firebasemessaging-without-using-google-services-json-to-support-multiple-project), [4](https://stackoverflow.com/questions/37634767/how-to-connect-to-more-than-one-firebase-database-from-an-android-app/37643374#37643374)), so a single official app build can support individual Firebase accounts.  
Alternatively whoever runs the Playstore account could also run the Firebase account.

**Comment by jmattheis** [comment]
This would require each user of gotify to register a Firebase account, and it
also wouldn't work for phones that doesn't have Google Play Services.

I'm closing this as out of scope, as gotify should not depend on any
third-party services.

**Comment by AndreKR** [comment]
> This would require each user of gotify to register a Firebase account

No, this would give each user the option to enable FCM if they want.

> gotify should not depend on any third-party services

It already "depends" on Android, several Gradle dependencies and a server that can run an executable. I don't really see how optional FCM support would be much different.

For users that don't want to use FCM there would be no change, neither in the build process nor in the usage.

**Comment by jmattheis** [comment]
> It already "depends" on Android, several Gradle dependencies and a server that can run an executable. I don't really see how optional FCM support would be much different.

Well, it's different, FCM will stop working if google stops the servers, this
won't happen with dependencies as there are mostly open source and aren't bound
to servers.

Adding FCM optionally would work, but I rather have one solution that works for
everyone, because it makes the app easier to maintain.

**Comment by voruti** [comment]
Old issue, i know, but I would also like to have this...

**Comment by jmattheis** [comment]
@voruti Have a look at https://github.com/supabase/supabase

**Comment by AndreKR** [comment]
@jmattheis I don't think supabase has anything to do with what is asked in this issue. This issue is about supporting "Firebase Cloud Messaging" which is a way to notify Android devices to wake up and process some incoming event. It is completely distinct from other "Firebase" services and I have no idea why Google decided to merge all those different service into one brand, it just creates confusion IMHO.

Supabase does not seem to have an equivalent feature to FCM, and probably for a good reason. It makes sense to handle push connections from all apps bundled together and also with background execution limits it makes sense to let a system component handle push notifications.
