### ISSUE TITLE
base64 encoded image isn't shown in app, the return

### ISSUE THREAD

**Issue by desbma** [gotify/android#164]
Followup to #107 

To reproduce:
```
(
python3 << EOF
import base64
import json
import requests
img_data = requests.get("https://upload.wikimedia.org/wikipedia/commons/a/a9/Example.jpg").content
markdown = f"![Image](data:image/jpeg;base64,{base64.b64encode(img_data).decode('ascii')})"
post_data = {
    "title": "Markdown image tests",
    "message": markdown,
    "priority": 5,
    "extras": {
        "client::display": {
            "contentType": "text/markdown"
        }
    }
}
print(json.dumps(post_data))
EOF
) | curl  -H "Content-Type: application/json" -H "X-Gotify-Key: REMOVED" -X POST --data-binary @- 'https://REMOVED/message'
```

The embedded image is shown correctly in the server web UI :
![Selection_2021-03-19_13-43-10](https://user-images.githubusercontent.com/1145175/111782287-1fdf7e80-88b9-11eb-96e0-3ae8f58fcef8.png)

But not in the Android app (notification bar or app screen) :
![Screenshot_20210319-134040](https://user-images.githubusercontent.com/1145175/111782496-5b7a4880-88b9-11eb-91d5-8e793c8442d1.png)

**Comment by jmattheis** [comment]
Should be fixed with https://github.com/gotify/android/commit/c45c19b968c3eecaf40d28caab73a3e79234ed27

**Comment by desbma** [comment]
With version `2.1.2` the image is shown in the app screen, but in the notification area the markdown code with base64 data is shown.

**Comment by jmattheis** [comment]
https://github.com/gotify/android/issues/74
