### ISSUE TITLE
Dark theme switch to light theme without a reason

### ISSUE THREAD

**Issue by ngosang** [gotify/android#166]
Gotify/Android 2.1.0

First of all, I see a lot of re-connection messages in the logs like https://github.com/gotify/android/issues/153 but I don't know if it could be related.

Steps to reproduce:
* Enable dark theme
* After few hours or days the theme changes to light theme
* If I force close the app, in the next start the theme is dark as expected

I guess it's related to disconnections but I can't be sure. I can't find exceptions or related traces in the logs when this happens.

**Comment by jmattheis** [comment]
The log view refreshes every x seconds, this probably resets the scroll position. If someone wants to fix this I'd be happy to accept a PR for this.

**Comment by jmattheis** [comment]
This is very likely not related to the disconnects. What's your android version and have you [disabled battery optimization](https://github.com/gotify/android#disable-battery-optimization)?

**Comment by ngosang** [comment]
Android 7.0
Yes, it's disabled. The app is always open (I see the notification) and it's working but the theme breaks after few days.

**Comment by ngosang** [comment]
My new phone has Android 11 and much more RAM. I can not reproduce the issue here.
