### ISSUE TITLE
Feature Request: Recycle Bin

### ISSUE THREAD

**Issue by spinnaker1** [gotify/android#172]
Please implement a recycle bin to store the deleted messages.

Especially with swipe to delete on Android, it's very easy and fast to delete messages (accidentally) and currently there is no way to recover them. A recycle bin is really useful.

**Comment by jmattheis** [comment]
I don't think this is in scope for the gotify project, as it tries to be as simple as possible (backend and clients). There is an undo toast message after you delete a message.

**Comment by spinnaker1** [comment]
Every program has a recycle bin (for a reason). And I doubt a recycle bin is adding any complexity to the Gotify simplicity. Users who don't want their massages deleted to recycle bin, could easily set an option "don't use recycle bin".

**Comment by disconn3ct** [comment]
Is that undo popup available on the web version? And is the duration configurable? Does it show after "delete all"?

**Comment by jmattheis** [comment]
@disconn3ct No.

**Comment by disconn3ct** [comment]
Does that toast address the issue anywhere outside of mobile devices? In the web UI, "permanently delete everything" is immediately next to "make sure I'm caught up" with no confirmation or undo. I hate "everyone else is doing it" examples but it really does seem like a concept of 'read-but-not-deleted' is minimally standard for notification apps, even without history or undo or any other gravy. (Conversely, if gotify is intended only for ephemeral notifications then I don't understand why it has the complexity of a db at all, even sqlite.)

**Comment by jmattheis** [comment]
> Does that toast address the issue anywhere outside of mobile devices?

No.

> In the web UI, "permanently delete everything" is immediately next to "make sure I'm caught up" with no confirmation or undo.

I'd be okay with a confirmation dialog when hitting delete all.

>  I hate "everyone else is doing it" examples but it really does seem like a concept of 'read-but-not-deleted' is minimally standard for notification apps, even without history or undo or any other gravy.

There was an issue about this https://github.com/gotify/server/issues/21 but I deemed it as not necessary.
