### ISSUE TITLE
Strike-through support missing in markdown

### ISSUE THREAD

**Issue by stefanberndtsson** [gotify/android#173]
Strong (`_, *`) and emphasis (`__, **`) both work fine in markdown notifications, but strike-through (`~~`) does not. 

It works in the markdown presented in gotify/server, but not the android client.
It would be nice to be able to use that style as well.

**Comment by jmattheis** [comment]
This requires an extension for the markdown library https://noties.io/Markwon/docs/v4/ext-strikethrough/ I'm open to accept PRs for this.
