### ISSUE TITLE
WebSocket reconnect not using the proxy

### ISSUE THREAD

**Issue by s-chNE-O** [gotify/android#175]
Hello,

I am currently in the setup of a new gotify server using the android app.

It all seems to work just fine setting up the nginx reverse proxy using the provided details in your doc.
But now I've gone and closed the port that i use on the gotify server (19443) from the outside only, local interface still works and so does the website via https/443.

The gotify server runs under `https://my-domain.com/gotify/` as the `/` is used for my netdata application which uses the goitfy api splendidly.

Since then I always seem to time out after the first `WebSocket: Closing existing connection`
The app then (only sometimes as it seems) tells me via notification something like `Connection lost - Reconnecting in XXXX`, other times I have to manually check as it still says `Listen to https://my.domain.com...`

As the log (see below) indicates it seems that the app still tries to connect to the gotify port yet on a refresh or restart of the app it uses the https/443 just fine, even collects all the messages. Hence i am unsure whether this problem arises from the app or from the server.

Am i missing something? I've tried `https://my-domain.com:443/gotify/` in the app as well, not working either.

Android app version :: 2.1.2 (via fdroid, big thanks for that)
Android version :: 10
Gotify version :: 2.0.22 amd64, binary from your website
Server OS :: Ubuntu 20.04.2 / 5.4.0-73 kernel, latest updates
NGINX version :: nginx/1.18.0 (Ubuntu), built with OpenSSL 1.1.1f  31 Mar 2020

Gotify server config :: [gotify-config.txt](https://github.com/gotify/android/files/6546967/gotify-config.txt)
Android log :: [gotify-android-log.txt](https://github.com/gotify/android/files/6546884/gotify-android-log.txt)
NGINX and site config :: [nginx-config.txt](https://github.com/gotify/android/files/6547090/nginx-config.txt)

If any more information is needed ill provide them asap.

Any help is greatly appreciated. Thanks for your time and this project.

**Comment by jmattheis** [comment]
Could you try to force close the application, maybe the service has the old url cached or something similar.

**Comment by s-chNE-O** [comment]
`Have you tried turning it off and on again.` No. I didnt.

That solved the problem and i feel kinda dumb now. Ive tested it yesterday and closed the app in the meantime. Now I know I cant trust android with the closing-the-software thing at all. Thank you very much!

**Comment by jmattheis** [comment]
No problem, this is most likely a bug, as the android service won't be restarted / killed on logout.
