### ISSUE TITLE
"Exit" button

### ISSUE THREAD

**Issue by tomsquest** [gotify/android#177]
Hi,

Stumble upon Gotify, and it is exactly what I needed. 
Working in less that 15 minutes ! :+1: 

I notice that there is no **Exit** button in the Android app. Syncthing, another excellent service, has one.

I try to be energy-savvy in my life, and stopping the app when not needed is better for me.
I do know that I can long-click on the notification and kill the app, but meh.

- Do you think it is a good idea ?
- Do you think it is a good "first feature" ?

**Comment by jmattheis** [comment]
Hey, 

I rather keep it simple and not duplicate functionality. If you don't want to run gotify in the background, you can restrict background usage inside android. This will kill the app, when it is not in foreground.

**Comment by tomsquest** [comment]
Hi Jannis,

Got it.
So far, I would say that waiting for Android to kill the app, where I could just exit it myself, is not the most efficient way. And even, I would have to re-disable the battery optimization each time when I do want Gotify in the background for a long time.

Here I try to not make a point of just my usecase, but the more general one of battery saving one.

May I _seduce_ you with a Pull-Request adding an Exit button :heart_decoration: ? :smile: 

_don't be worried, I know nothing about Android, just that it is a kind of robot. Expect a shipping date around 2033_

**Comment by jmattheis** [comment]
:D, yeah, I'm in favor of battery life, but this seems like an edge-case which will only affect a tiny part of the user base, thus, I'll close this issue.
