### ISSUE TITLE
No Update from 2.1.3 to 2.2.0 (github versions) possible.

### ISSUE THREAD

**Issue by pm-pm** [gotify/android#186]
Hallo,
what did i do wrong? Android 11 Smartphone during manual instllation says: "Update from 2.1.3 to 2.2.0 not possible".

I am using the github version. Version 2.1.3 is running well and of course i could remove 2.1.3 first before installing 2.2.0, but i would like to know the reason why an update is not possible. Did i not read everything? Is there a mistake?

Thanks
pm-pm

**Comment by jmattheis** [comment]
Hey, this should be fixed now. Could you try to redownload & reistall the apk? 

Google forced a change in the app signing with android 11. I fixed this manually for the Google play build but didn't re-uploaded the apk on the release page. The relevant changes are here https://github.com/gotify/android/commit/802e30fd3690a0f60d9753402d58171cf5ee3e03.

**Comment by pm-pm** [comment]
Hello jmattheis,
thanks a lot. It works now perfectly. :-)
