### ISSUE TITLE
Notification Grouping

### ISSUE THREAD

**Issue by sporkbyspork** [gotify/android#187]
I'm testing Gotify as a replacement for a Telegram bot sending me details about my home automation. Works great so far!

The notifications not being grouped make the daily use a bit of a hassle. My use cases tend to generate quite a lot of notifications in a very short amount of time.

On my WearOS watch, I have to swipe away all notifications one by one.
Telegram FOSS's notifications, on the other hand, can all be dismissed with a single swipe.

**Comment by jmattheis** [comment]
Gotify uses the native notification groups which are supported with Android 7.0 https://developer.android.com/training/notify-user/group

Does your watch have Android >= 7.0?
