### ISSUE TITLE
[FR] Notification on connection lost / change

### ISSUE THREAD

**Issue by mad73923** [gotify/android#188]
Since the Push-Servers run on private machines or behind VPNs, the connection might not be reliable.
To inform the user about a connection loss, a additional notification channel would be nice.

**Comment by mad73923** [comment]
Working on this at https://github.com/mad73923/gotify_android
Having trouble to test due to #189

**Comment by jmattheis** [comment]
There is already a silent notification for connection changes. If you've a more recent android phone (>= 8.0) then you can change the intrusiveness of the "Gotify foreground notification" notification channel.

**Comment by mad73923** [comment]
Yes, thats clear to me. I have this notification channel setup as silent and minimized since it is always active.
What I like to add is a notification specifically for connection errors which is non-sticky and only shows/notifies if there is a error.
What do you think about that?

**Comment by mad73923** [comment]
PR #190

**Comment by jmattheis** [comment]
I don't think this is really needed, at least not as a default. It is perfectly fine for the connection to break with mobile network, and I don't think a user wants to be notified every time. There are some tickets from people that disliked that in android < 8 the foreground notification made a noise every time the connection broke.

**Comment by mad73923** [comment]
I see!
My intent was primarily detecting server crashes, not connection losses. I don't think this is differentiable from the socket perspective, is it?
What if we implement this only for Android > 8?

**Comment by jmattheis** [comment]
People disliked it in android < 8 I don't think they want it in android > 8. If you want to detect server crashes, then you probably want to host gotify on a separate server with something like https://github.com/louislam/uptime-kuma which has support for sending gotify message on status changes.

**Comment by Sternagfonkel** [comment]
As a user I would expect, that after configuration process (setup applications,...) Gotify just works. I understand that in case of a network connection loss it can not work, but any other failure should not happen at all.
If a crash happens anyway, this would be a very exceptional situation which I think should not be handled by a regular notification from the appplication itself (I don't know any application which behaves like that and sends a notification if the server/service is down).
Also user and administrator are not always the same person. While an admin might be interested in such status information, the user doesn't care.
So I think it is not a good idea to do a notification in such a case, but maybe it would be a compromise to write such events to the logs?

**Comment by jmattheis** [comment]
All errors releated to the websocket connection will be logged already.

**Comment by mad73923** [comment]
Alright, thanks for the good arguments and for looking for compromises.
I'll close this and the PR for now.

**Comment by Waldorf3** [comment]
Sorry to reopen this issue. I run a separate instance with uptime-kuma, gotify and other control apps, and have experienced service failure for the server, which means gotify is no longer available to notify me about this.  It is for this reason I would like gotify to notify me that it lost connection to the server. I know it shows a message, but I would like to be able to give this highest priority as it's a service failure - not of gotify but the server where gotify runs. Ordinarily I would have s second instance of gotify on another server, but I don't think the app supports dual servers, and in any case that would be a bit of an overkill,at least in my case.

**Comment by jmattheis** [comment]
@Waldorf3 See https://github.com/gotify/android/issues/219

**Comment by Waldorf3** [comment]
Thanks!  Google really are hiding those settings well....
