### ISSUE TITLE
Build fails with package javax.annotation

### ISSUE THREAD

**Issue by mad73923** [gotify/android#189]
Trying to build the app throws the following error (13 occurrences):
```
error: package javax.annotation does not exist
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-24T18:39:01.386+02:00")
```
Same as #160 . But the solution isn't described well / I couldn't follow.

**Comment by jmattheis** [comment]
Are you using java8?

**Comment by mad73923** [comment]
I could set it to 1.8 by the help of this:
https://developer.android.com/studio/intro/studio-config#jdk
This info was missing.
