### ISSUE TITLE
Add server via QR code

### ISSUE THREAD

**Issue by PanderMusubi** [gotify/android#195]
Offer adding a server via QR code that is scanned from the web GUI on the server.

The QR code contains at least the URL and optionally:
- username
- password
- expiration date time of the code
- some simple form of encryption
- extra confirmation or reporting in the web GUI when an app is connecting via QR code
- a unique number for automatic invalidation of the code when the code is used once successfully

These optional items can be configurable by the admin.

Implementing this will allow users to more quickly add a server without typing possibly long strings and without making typing errors.

Implementing this will also need work on the side of the server in the web GUI.

**Comment by jmattheis** [comment]
While useful, I'd like to keep gotify as simple as possible. I don't think that adding server is something that needs to be optimized because it is not done very often.
