### ISSUE TITLE
More recognizable notification icon

### ISSUE THREAD

**Issue by PanderMusubi** [gotify/android#196]
The current notification icon is an outline of the highly detailed logo. This unfortunately does not make it very recognizable. It can look like a smudge or country outline and a user must spend more time recognizing it as Gotify.

![Screenshot_20211102-061533](https://user-images.githubusercontent.com/198964/139817786-2e229174-d6da-435f-83d2-fa557f51e7f1.png)

Also, it is in contrast with more well designed and easier to recognize notification icons from other applications.

Please have a more clear and recognizable notification icon. Below is an idea of how that can look. This is only as reference input for a designer.

![pos](https://user-images.githubusercontent.com/198964/139818252-4c8a367f-6239-476c-94bc-6784bced6db1.png)

**Comment by PanderMusubi** [comment]
Once this PR has been merged https://github.com/gotify/logo/pull/4 the notification icon can be upgraded here.

**Comment by PanderMusubi** [comment]
Shall I make a PR for this?

**Comment by jmattheis** [comment]
@PanderMusubi sure

**Comment by PanderMusubi** [comment]
https://github.com/gotify/android/pull/243
