### ISSUE TITLE
Less data in notification drawer

### ISSUE THREAD

**Issue by PanderMusubi** [gotify/android#197]
Data or status shown in the notification drawer is currently:

![Screenshot_20211102-103212_Trebuchet](https://user-images.githubusercontent.com/198964/139822297-86270e0b-811a-4f01-b26a-38496410c54c.png)

Proposal to prevent shoulder surfing https://en.wikipedia.org/wiki/Shoulder_surfing_%28computer_security%29 is to not show `Listening to ...` and change the bold header to `Gotify is connected` or `Gotify is not connected, retrying in x minutes` when there is no internet connection. (This wording is slightly shorter and does not have the word failed. It is not a failure when purposely being in flight mode e.g.) Or whatever wording is more relevant, see the example of Syncthing.

Implementing this will take up less space in the notification drawer (which at times can get overcrowded) and prevent showing possibly sensitive URL to people that need not see that URL.

**Comment by jmattheis** [comment]
I don't think the url is really confidential, as the access is secure via credentials, but I'm willing to take PRs for this.

**Comment by PanderMusubi** [comment]
Thanks, looking forward to testing the next version.

**Comment by cyb3rko** [comment]
I guess can be closed as it's implemented by PR #214.
