### ISSUE TITLE
I want to modify the logo layout

### ISSUE THREAD

**Issue by lovessea** [gotify/android#206]
I want to change the layout of the page so that the App has more room to display the body content(make web pages better displayed on mobile devices and app for Android)
As shown in the figure below.
![20220115125734](https://user-images.githubusercontent.com/13111345/149609678-e5884f9e-450a-4e62-adb2-9408aa798a11.png)

**Comment by jmattheis** [comment]
Oke.

**Comment by lovessea** [comment]
in server  and android app ,especially in app changes,the new layout is better displayed on markdown's page
