### ISSUE TITLE
Android App - Login to server works fine but App unable to register as a client and unable to see any Apps on server

### ISSUE THREAD

**Issue by baudneo** [gotify/android#209]
I updated the Android client yetserday and ever since I have not been able to get gotify to work properly. When I send a notification the web app receives it fine but the android clients do not receive any notifications. The android clients are not able to push any messages either as it says there are no apps to push a message to. The logs on android device don't have any information that I can see to help troubleshoot, the logs from using docker logs --follow also do not have nay pertinent information that I can see.

I didn't change anything in my setup that would cause this, the only thing changed form yesterday when it was working is the android gotify client was updated. Has anyone else seen this problem and found a fix?

Thanks.

Edit: gotify is behind openresty reverse proxy which is being proxied by cloudflare. The set up was working fine yesterday, even when I am on local LAN the gotify android client cant successfully register as a client or see any 'Apps' to push a message to.

**Comment by baudneo** [comment]
It seems to be some sort of error with docker, after leaving the logs running for awhile I saw this output to stdout
```
WebSocket: ReadError read tcp 172.21.0.2:80->10.0.0.42:44510: i/o timeout
```
172.21.0.2 is in the docker network and the other IP is my phone locally.

**Comment by jmattheis** [comment]
Can you try to connect directly to gotify without proxying it through openresty / cloudflare? Add the full log from gotify/server gotify/android and add your reverse proxy configuration.

**Comment by baudneo** [comment]
I have also tried to direct connect on local lan with same results. I removed everything and reinstalled and it all seems to be working. I'm assuming it was something to do with docker and the websocket connection.

All is well now.
