### ISSUE TITLE
Notifications not appearing but dots do

### ISSUE THREAD

**Issue by rightsaidfred99** [gotify/android#210]
Recently setup gotify

I managed to get messages working via post.

The messages come through to my android device.
However only the notification dot on the app icon. Nothing I do with priority or such ends up with the expected behavior of having a notification popup when a message is received.

I'm not sure how to post any logs.

Also using GrapheneOS if it helps.

**Comment by jmattheis** [comment]
Make screenshots of the log. If there is a notification dot then the app has received the notification but doesn't display it, have a look at the android native notification settings of the app, maybe they are disabled for gotify/android somehow.

**Comment by rightsaidfred99** [comment]
OK, I'll try. 

In the interim I noticed that there is a persistent notification by default. If one is to hide this but keep the others on, maybe that would be it. 

![Uploading Screenshot_20220209-125810.png…]()

**Comment by jmattheis** [comment]
Looks like you received 2 min  priority messages, they normally don't show up. How have you sent high priority messages?

**Comment by rightsaidfred99** [comment]
Ah ok, in that case it's probably on my end not a bug. 

I'm using Synology's System UI, so it's using the POST method, but I think I may have not parsed the priority via this UI to Gotify which would now explain everything. Thanks for your patience and helping me out!

**Comment by rightsaidfred99** [comment]
If anyone else comes across the issue, it's the same as this post

https://github.com/gotify/server/issues/312

I guess it would be indeed useful to configure message priority another way because with the platform I use, it doesn't seem possible
