### ISSUE TITLE
fire stick support ???

### ISSUE THREAD

**Issue by tidder99** [gotify/android#211]
hi all amateur programmer here 
wondering if there could be any support for the fire stick added or a spin off app
I installed the original Android app it works 99% 
it puts messages in the notification manager
but doesn't Pop them up on screen
I think it's something to do with how the fire os wonts notifications to be prioritised
[Amazon Device Messaging (ADM) and local notifications on Fire TV](https://developer.amazon.com/blogs/appstore/post/6c32f2d7-4770-416f-bcbd-a891f885a0e8/amazon-device-messaging-adm-and-local-notifications-on-fire-tv)
I fiddled with the code a bit but it's beyond me
but it sure does feel like all you have to do with it is jigger with the notifications

**Comment by jmattheis** [comment]
Hey, you probably have to add the setPriority in here https://github.com/gotify/android/blob/master/app/src/main/java/com/github/gotify/service/WebSocketService.java#L296
In newer android versions this is handled via NotificationChannels which gotify uses. I don't really intend to support old android versions, thus, I'll not include this inside the app.

**Comment by tidder99** [comment]
thanks it works kind of
the fire TV doesn't allow pop-ups when media is playing
I can see why you don't want to support other things like fire TVs
I'm going to tinker with it some more and see if I can get it the way I like it
thanks for the help
