### ISSUE TITLE
"bigImageUrl" - Unable to get it working

### ISSUE THREAD

**Issue by baudneo** [gotify/android#215]
I was first trying with more complex URL's but even the supplied URL https://placekitten.com/400/300 does not work. This is a snippet from the gotify android app logs ->

```
 "extras":{"android::notification":{"bigImageUrl":"https://placekitten.com/400/300"},"client::display":{"contentType":"text/markdown"}},"date":"2022-03-01T15:05:29.469066599Z"}
```
The `contentType` extra option is working but the bigImageUrl is not, I had the same problem with the 'click' extra as well.

Here is the python code I am using to send the message to Gotify, To see the Image I embedded it into the markdown and that works (image URL removed in this example)

```
data = {
                            "title": f"Camera: {g.config.get('mon_name')} - Event: {g.eid}",
                            "message": test_msg,
                            "priority": 6,
                            "extras": {
                                "client::display": {"contentType": "text/markdown"},
                                "android::notification": {"bigImageUrl": "https://placekitten.com/400/300"},
                                # "client::notification": {
                                # "click": {
                                #     "url": f"{g.api.portal_url}/cgi-bin/nph-zms?mode=jpeg&scale=50&maxfps=15"
                                #     f"&buffer=1000&replay=single&event={g.eid}"
                                #     f"&connkey={randint(0, 99999999)}&{push_zm_tkn}"
                                # }
                                    # "bigImageUrl": f"{g.api.portal_url}/index.php?view=image&eid={g.eid}&fid=objdetect&{push_zm_tkn}",
                            },
                        }
                        resp = requests.post(f"{goti_host}/message?token={goti_token}", json=data)
```

The kitten image is not showing in the android notification drawer or anywhere, I am uncertain how I can debug further.

Android App version is 2.3.3 and server is 2.1.4

**Comment by jmattheis** [comment]
Seems like I documented it wrong on the website, the `bigImageUrl` must be under `client::notification`.

**Comment by baudneo** [comment]
Thank you for clearing that up! it works as expected when enclosed in `client::notification`
