### ISSUE TITLE
Build instructions did not work for me.

### ISSUE THREAD

**Issue by PopeNobody** [gotify/android#218]
I did a git clone, read the readme, and did ./gradlew build, as instructed.

[gradlew.log](https://github.com/gotify/android/files/8235084/gradlew.log)

I've attached the output.  I spent a couple hours hacking on it yesterday, up to and including trying to rewrite the build.gradle's from scratch, and failed.

Tried again from scratch today, and this was the result.

**Comment by PopeNobody** [comment]
I was not sure if the "update client" text in the readme was instructions, or a log of something somebody already did.  So I went back and followed those instructions.

The result was this:

```
parse@penguin:~/src/gotify/android/client$ bash ./gradlew updateSwaggerCode

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.13'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by PopeNobody** [comment]
The gradle wrapper in the client directory downloaded gradle 2.6x, so I'm guessing this is not a commonly used path these days.  :)

**Comment by jmattheis** [comment]
Use Java 8 for building gotify/android.

**Comment by PopeNobody** [comment]
Thanks, that worked for me.

Want me to update the docs and put in a pull request?
