### ISSUE TITLE
Server availability monitoring 

### ISSUE THREAD

**Issue by MilorES** [gotify/android#219]
I did the test turning off the server... and at no time did it tell me that it was not available. 
Is this possible to check the status every X minutes?

**Comment by jmattheis** [comment]
The foreground notification will be updated every time the status of the connection changes, you can change the intrusiveness of this notification inside the android notification settings. (Default is silent)
![image](https://user-images.githubusercontent.com/14895212/158014924-2c24ce3d-ce5c-41f8-bd53-60bb10d63907.png)

**Comment by MilorES** [comment]
Thanks a lot

Well, now if you notify when you change state.
But then am I forced to always show the notification?

![Screenshot_2022-03-12-12-07-40-280](https://user-images.githubusercontent.com/7502697/158015878-0fc15af6-046c-47b3-ae91-0f0a18bb1b43.jpg)

I did several tests to hide it, I will keep trying.

**Comment by jmattheis** [comment]
Yeah, you probably cannot hide the notification if you want to receive the alerts when the connection is lost.
