### ISSUE TITLE
Links difficult to read in dark theme

### ISSUE THREAD

**Issue by axllent** [gotify/android#221]
I find it odd that this hasn't been reported before, or maybe I'm blind, but links in the app while using the dark theme are really hard to read, especially when the screen is dimmed. Can this be changed to something lighter or brighter please?

![Dark](https://user-images.githubusercontent.com/1463435/160107295-159d11b9-1615-49c4-9265-f22432c6d741.png)

**Comment by jmattheis** [comment]
I'm open to accept PRs for this.

**Comment by Sternagfonkel** [comment]
Is there a reference how a link should look and behave like if in dark mode? E.g. a design guideline or a relevant website/app?

**Comment by jmattheis** [comment]
@Sternagfonkel No there is no guideline, it should probably be similar to the webapp.
