### ISSUE TITLE
Allow select/zoom/pan of embedded images

### ISSUE THREAD

**Issue by baudneo** [gotify/android#222]
It would be great to be able to click the image in the notification and then be able to zoom and pan. I use PushOver and Gotify, PushOver has this built-in and I was hoping it could be implemented in Gotify?

I also throw my vote towards the critical alert / re-occurring vibrate/sound until user intervention like PushOver has as well. Are there any plans for webhooks as well?

Loving the new bigImageUrl for the drop-down drawer! Thanks for your hard work!

**Comment by jmattheis** [comment]
Seems useful.

**Comment by IanQuilter** [comment]
I agree that zoom and pan would be a really useful feature.

**Comment by baudneo** [comment]
Sure would, I use gotify for notifications from my custom object detection framework for zoneminder. I desperately need to be able to zoom in on some images. For my use case, it would drastically improve my user experience.
