### ISSUE TITLE
The advice about message‘s delete on app 

### ISSUE THREAD

**Issue by lovessea** [gotify/android#228]
1. Advised to remove  the delete button from the message list to simplify the page.   
2. Advice to delete the message through the delete button on the bottom page. 
3. Advice the delete button on the bottom page can through The Message Moving left or right let the delete button show. 
![微信图片_20220418092128](https://user-images.githubusercontent.com/13111345/163740301-d57c204b-1933-493e-b087-fbd3ffa193e5.jpg)

**Comment by jmattheis** [comment]
1. No, already discussed in here https://github.com/gotify/android/pull/99
2. Do you mean adding a delete button to the notification?

**Comment by lovessea** [comment]
ok，you are right,just didn't see the historical issues.
But  i advice through the button by swiping to show and to delete not through swiping to delete,The current version is liable to be deleted by mistake.Thank you!

**Comment by lovessea** [comment]
Left swipe to display button of delete  and click the button to submit a deletion request.

**Comment by lovessea** [comment]
I modified this file : message_item.xml maybe you can use it

<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical"
    android:padding="10dp"
    android:background="?android:colorBackground">


    <ImageView
        android:id="@+id/message_image"
        android:layout_width="30dp"
        android:layout_height="30dp"
        android:contentDescription="@string/message_image_desc"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <TextView
        android:id="@+id/message_date"
        android:layout_width="wrap_content"
        android:layout_height="20dp"
        android:text=""
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintTop_toTopOf="parent" />


    <TextView
        android:id="@+id/message_title"
        android:layout_width="334dp"
        android:layout_height="21dp"
        android:layout_marginTop="4dp"
        android:layout_marginEnd="8dp"
        android:text=""
        android:textSize="16sp"
        android:textStyle="bold"
        app:layout_constraintEnd_toStartOf="@+id/message_date"
        app:layout_constraintStart_toEndOf="@+id/message_image"
        app:layout_constraintTop_toTopOf="parent" />

    <TextView
        android:id="@+id/message_text"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginTop="24dp"
        android:textIsSelectable="true"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.526"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/message_title" />













</androidx.constraintlayout.widget.ConstraintLayout>

**Comment by jmattheis** [comment]
Like I said, it was already discussed if the delete button should be removed, and it was decided that it will stay. I also don't like the extra button for delete on swipe, it just make it to difficult to delete something, there is an undo button so it is possible to undo a deleted message.
