### ISSUE TITLE
Client certificate support?

### ISSUE THREAD

**Issue by polizz** [gotify/android#229]
I would like my reverse proxy to utilize client certificates to control access to gotify. This is working for the gotify web site and a computer with the cert installed. However, the android application does not seem to try to use a locally installed client cert on the android device. Can this support be added?

**Comment by polizz** [comment]
I'm working on a PR for this. I was thinking of using the built-in Android user cert picker, but I don't think that's in the earlier versions of Android, which I think this project is trying to support. The code also got terribly complicated due to needing to bring that picker up from a different thread. I'm thinking of now going down the same road the app currently does for CA certs - file choose activity and raw load the cert that way. I'm not a Java/Android developer by day, so it may be rough.

I'm currently thinking the best place for this is in the ```advanced settings``` for the login activity.

![image](https://user-images.githubusercontent.com/10888433/164762190-1eecab0c-5fde-4466-86df-82f8fe72f61b.png)

Any other suggestions on direction?

**Comment by jmattheis** [comment]
It is fine, if the client certificate feature is only supported in newer android versions. So, it's okay to use the native certificate picker.

**Comment by jmattheis** [comment]
Duplicate #85
