### ISSUE TITLE
Connection failed time in notification

### ISSUE THREAD

**Issue by BilalBhatti** [gotify/android#234]
I think it would be much useful if we could see the time passed since server became inaccessible.

It could be as easy as **Connection failed since 32 mins, trying again in 9 minutes** OR **Connection failed at 02:00 PM, trying again in 9 minutes**

![image](https://user-images.githubusercontent.com/834893/171915140-eb8cdaf5-e844-4b7a-b200-ab40d18a36e9.png)

Its not an issue but feature request. I have to go to logs to check outage status.

**Comment by jmattheis** [comment]
Why is this useful? This seems not like a common use-case.

**Comment by BilalBhatti** [comment]
It is a use-case in a sense that if server goes down, we should know since when its went down. Trying again in some minutes doesn't convey any info like this.

**Comment by jmattheis** [comment]
What does it help you to know, when the server went down?

**Comment by BilalBhatti** [comment]
So that we can go and check the issue. Try to restore the outage for customers being served through that server.

**Comment by jmattheis** [comment]
But it doesn't matter when the error happened, only that it is currently down.
