### ISSUE TITLE
Image not shown in android, shown normally in server webui.  Due to redirect?

### ISSUE THREAD

**Issue by pdfrg** [gotify/android#244]
I read the open and closed issues, and while it looks like there are a couple of other similar closed issues, none of them seem to apply here.

From the android logs:
```
[2022-10-06](tel:2022-10-06)T18:40:[16.618](tel:16.618)Z INFO: Entering LogsActivity
[2022-10-06](tel:2022-10-06)T18:40:[05.061](tel:05.061)Z INFO: WebSocket(16): received message {"id":[15187](tel:15187),"appid":11,"message":"Hello: ![](https://coverartarchive.org/release/983ae253-215e-4f6c-8411-fa7ddcec2d94/front-500)\n\n### line2\n\nline3","title":"Jellyfin testing","priority":5,"extras":{"client::display":{"contentType":"text/markdown"}},"date":"[2022-10-06](tel:2022-10-06)T14:40:[04.713997498-04](tel:04.713997498-04):00"}

[2022-10-06](tel:2022-10-06)T18:39:[59.942](tel:59.942)Z INFO: WebSocket(16): received message {"id":[15186](tel:15186),"appid":11,"message":"Hello: ![Gotify Logo](https://gotify.net/img/logo.png 'optional title')\n\n### line2\n\nline3","title":"Jellyfin testing","priority":5,"extras":{"client::display":{"contentType":"text/markdown"}},"date":"[2022-10-06](tel:2022-10-06)T14:39:[59.534221649-04](tel:59.534221649-04):00"}
```
The Gotify logo shows normally in both the server webui and the android app (timestamp 18:39), but the album cover from coverartarchive.org only shows normally on the server webui, not on the android app (timestamp 18:40).  Instead, a placeholder square of some sort is shown.  Everything else except the urls are the same.  

Of course, the Gotify logo is directly linked, while the cover art redirects.  I don't know why this is handled by the server webui, but not by the android app.  On one other issue, I can recall a comment about the android markdown library handling markdown differently.  I don't know if that's what is happening here, or if anything can be done to fix this.   

The above are just from a simple test script.  I have the Jellyfin webhook plugin configured for Gotify and have basically all the notifications set up how I want them, but can't get album art to work for audio start/stop notifications.  There is no way I can find to get the image directly from Jellyfin based on what is output from the webhook, so this is my workaround.  I have an issue opened so far without any response there.

Thanks for Gotify, I love it.  And sorry if my terminology is all wrong, clearly I am no programmer.

**Comment by jmattheis** [comment]
I've played a little bit with the url, it seems it sometimes redirect to an url that doesn't exist.

```
$ http 'https://coverartarchive.org/release/983ae253-215e-4f6c-8411-fa7ddcec2d94/front-500'
HTTP/1.1 307 TEMPORARY REDIRECT
Location: https://archive.org/download/mbid-983ae253-215e-4f6c-8411-fa7ddcec2d94/mbid-983ae253-215e-4f6c-8411-fa7ddcec2d94-19120789325_thumb500.jpg
...

See: https://archive.org/download/mbid-983ae253-215e-4f6c-8411-fa7ddcec2d94/mbid-983ae253-215e-4f6c-8411-fa7ddcec2d94-19120789325_thumb500.jpg

$ http 'https://archive.org/download/mbid-983ae253-215e-4f6c-8411-fa7ddcec2d94/mbid-983ae253-215e-4f6c-8411-fa7ddcec2d94-19120789325_thumb500.jpg'
HTTP/1.1 302 Found
Accept-Ranges: bytes
Connection: keep-alive
Content-Type: text/html; charset=UTF-8
Date: Thu, 06 Oct 2022 19:28:45 GMT
Location: https://ia801307.us.archive.org/1/items/mbid-983ae253-215e-4f6c-8411-fa7ddcec2d94/mbid-983ae253-215e-4f6c-8411-fa7ddcec2d94-19120789325_thumb500.jpg%0A
Referrer-Policy: no-referrer-when-downgrade
Server: nginx/1.18.0 (Ubuntu)
Strict-Transport-Security: max-age=15724800
Transfer-Encoding: chunked

$ http 'https://ia801307.us.archive.org/1/items/mbid-983ae253-215e-4f6c-8411-fa7ddcec2d94/mbid-983ae253-215e-4f6c-8411-fa7ddcec2d94-19120789325_thumb500.jpg%0A'
HTTP/1.1 404 Not Found
...

$ http 'https://ia801307.us.archive.org/1/items/mbid-983ae253-215e-4f6c-8411-fa7ddcec2d94/mbid-983ae253-215e-4f6c-8411-fa7ddcec2d94-19120789325_thumb500.jpg'
HTTP/1.1 200 OK
...
```
I cannot reproduce it at the moment, but could you recheck if the image now works inside the app. You maybe have to clear the image caches by refreshing gotify here.


![image](https://user-images.githubusercontent.com/14895212/194404482-4d9f743f-4db5-48a6-9b39-adcd680657f7.png)

Currently, the image renders correctly on my phone.

![image](https://user-images.githubusercontent.com/14895212/194404768-af003e29-f6a1-4a72-a922-eb5b8c283aca.png)

**Comment by pdfrg** [comment]
I did the refresh and now it shows on my phone, too.
Thank you for the quick response and for your help.
