### ISSUE TITLE
Major Refactoring/Updating (Butterknife -> ViewBinding, Kotlin, other updates)

### ISSUE THREAD

**Issue by cyb3rko** [gotify/android#245]
Hello there,

I would like to update some parts of the app to make it future-proof, for example:

- [x] Move from deprecated Butterknife to ViewBinding (as recommended by the dev of Butterknife)
- [x] Maybe move from Java to Kotlin
- [x] Update some dependencies

Do you consider any of these points or do you rather want to keep the current codebase?

**Comment by jmattheis** [comment]
Hey @cyb3rko, all your points sound good to me. It would probably be cool, if these changes were made incrementally, so that the Pull Requests don't get too huge.

**Comment by cyb3rko** [comment]
Yeah of course, I'm a friend of split up pull requests and tidy git commits :)

**Comment by cyb3rko** [comment]
First step is done, refactoring from Butterknife to ViewBinding is done.
Just waiting for the compact layout thing to be merged, as I built on that codebase.
Then I can open a pull request to merge it.

Otherwise we would have resolve merge conflicts :)

**Comment by jmattheis** [comment]
Alright, I probably won't be able to review anything until the weekend. Just a heads-up (:

**Comment by cyb3rko** [comment]
No problem, take your time :)
Currently busy as well...

**Comment by mar565** [comment]
Can you consider using the alarm channel for high priority messages? By default my phone is on mute, but I would like to be alerted by sound if something important happens.
Here is a [link](https://stackoverflow.com/questions/50881732/playing-sound-on-the-alarm-channel-on-android) that may help with my request.

**Comment by cyb3rko** [comment]
@mar565 This topic does not really fit here in this pull request, please consider opening a [new issue](https://github.com/gotify/android/issues).

**Comment by cyb3rko** [comment]
@jmattheis What do you think?
Should this app move to Kotlin?

If so, should I first focus a redesign?

**Comment by jmattheis** [comment]
@cyb3rko Tbh, I'm not really sure if it would be worth the effort. Do you think it would improve the gotify/android codebase?

**Comment by cyb3rko** [comment]
I think it would.

1. Kotlin has been the Android standard for years now.
2. If gotify/android makes the switch to Kotlin it's more modern and 'futureproof' regarding the codebase and upcoming contributions.
3. It would simplify the code as most Kotlin expressions are much easier to use and to read than Java expressions.

**Comment by jmattheis** [comment]
Okay, I'd be fine with the migration, but the http client stuff in ./client should stay as it, because it is generated.

**Comment by cyb3rko** [comment]
Finished:

- #248 Refactor Butterknife to ViewBinding
- #252 Major build updates
- #251 Increase minSdkVersion
- #258 Codebase rewrite to Kotlin
