### ISSUE TITLE
Duplicate splash screen

### ISSUE THREAD

**Issue by cyb3rko** [gotify/android#247]
Beginning with Android 11 or Android 12 every app you open shows a native splashscreen.
Additionally this app currently shows an own splashscreen, we could merge those two into one native one.

Here's the problem (on Android 13):

https://user-images.githubusercontent.com/46033730/194776278-8111af1a-5a92-4312-b44d-31198bf3f051.mp4

**Comment by jmattheis** [comment]
Does android allow executing code while the native splash is active? Currently, gotify checks if the token is valid? If we merge it, does this still work in older android versions?

**Comment by cyb3rko** [comment]
You can.
The "new" splash screen will only be shown on new splashscreens by default, but you can make it backwards compatible.
