### ISSUE TITLE
Update *SdkVersion to 33

### ISSUE THREAD

**Issue by jmattheis** [gotify/android#250]
Starting November, Google will require the targetSdkVersion to be >= 31, otherwise app updates will be rejected.
https://developer.android.com/google/play/requirements/target-sdk

We could probably think about increasing the minSdkVersion.

**Comment by cyb3rko** [comment]
Do you see a reason to increase the minSdk at the moment?

**Comment by cyb3rko** [comment]
Oh, but I think I was running the wrong Java version.
I will check tomorrow.

**Comment by jmattheis** [comment]
> Do you see a reason to increase the minSdk at the moment?

Yes, f.ex in android 12 (api version 31), all pending intents need a mutability flag, like https://developer.android.com/reference/android/app/PendingIntent#FLAG_MUTABLE this flag is only available in >= api version 23. With the current min version, we would have to create version checks everywhere like this:
```java
        PendingIntent pendingIntent =
                PendingIntent.getActivity(
                        this,
                        0,
                        notificationIntent,
                        Build.VERSION.SDK_INT >= Build.VERSION_CODES.M
                                ? PendingIntent.FLAG_IMMUTABLE
                                : 0);
```

But this is probably negligible, because gotify/android is a pretty small code base.

**Comment by cyb3rko** [comment]
Ah I see. To be fair the userbase which uses Android < api version 23 is pretty small.
Especially if you consider that techies, who use Gotify, usually don't use the oldest phones.

According to https://apilevels.com/, only around 2,4 percent of users still use an Android older than Android 6 (api level 23).
So yeah. I think we could upgrade the minSdk, you're right.

**Comment by jmattheis** [comment]
Yeah, the current installs of gotify look similar.
![image](https://user-images.githubusercontent.com/14895212/197329690-55c7d55a-7c1d-4826-a4b4-63bac7e4638f.png)

**Comment by jmattheis** [comment]
Tho, this doesn't include manuall installs and f-droid usage.

**Comment by cyb3rko** [comment]
Yeah, but manual installs and F-Droid installs shouldn't really differ that much.
That are 8 installs out of 4291 from the Play Store, that's okay I guess.

**Comment by jmattheis** [comment]
:+1:

**Comment by cyb3rko** [comment]
But I saw yesterday there's a lot to update.
Once I can get this to work, I could continue with tackling the duplicate splash screen.

Once that all is working and merged, I could try to update parts of the design.

**Comment by jmattheis** [comment]
The maven plugin is referenced in generated code, we probably should regenerate the client, it'll probably use the newer maven publish plugin, otherwise we can just remove the maven plugin as it isn't used. It isn't removed because then more changes are needed when regenerating the client.

**Comment by cyb3rko** [comment]
Updating some androidx dependencies worked (https://github.com/cyb3rko/android/commit/3edf2562333fdab0207b7640cbcf391fe87ef8df), but these are still pretty outdated as the dependencies included in the project are too old I think.

So I started with upgrading the Gradle Plugin from 4.0.0 to 7.3.0, which requires a newer Gradle version (7.4).
But it seems this gradle version again does not support the maven plugin anymore.

---

> The maven plugin is referenced in generated code, we probably should regenerate the client, it'll probably use the newer maven publish plugin, otherwise we can just remove the maven plugin as it isn't used. It isn't removed because then more changes are needed when regenerating the client.

Just like you mentioned we first have to tackle this problem then. How would that work? I never worked with the maven plugin, what can be removed from the build files? I can not really help there.

**Comment by jmattheis** [comment]
See https://github.com/gotify/android/tree/update-stuff

**Comment by cyb3rko** [comment]
Perfect, updates are almost done.
Do you know, what you've used `implementation 'androidx.legacy:legacy-support-v4:1.0.0'` for?

Because by removing it you find out, that only the SwipeRefreshLayout has to be manually imported, everything else seems to work.

**Comment by jmattheis** [comment]
Not sure, this dependency existed when I bootstrapped the android app. If it works without it, then feel free to remove it. But we should probably test the app with an android 6 emulator.
