### ISSUE TITLE
Feature request: add custom headers to every request to the server

### ISSUE THREAD

**Issue by OB-UNISA** [gotify/android#259]
## Feature request
Can you add a feature that allows adding custom headers to the requests from the phone to the server? This feature would be needed starting from the first connection when setting the URL.

My use case is that I'm using Cloudflare's Tunnels and I need to have Cloudflare's Access as the first authentication method. I could use Cloudflare's WARP on my phone but I'm already running another VPN and Android doesn't allow chaining VPNs.

Cloudflare's Access has an authentication method called Service Token which allows adding two Headers to the requests to be authenticated.

I tried to add the feature with static input and no UI on a forked repository and it works, but my knowledge is not enough to develop it as a feature for the app. 

## A simple implementation I tried
To make it work without refactoring too much code, I wrote a simple Interceptor which adds the two headers and added the interceptor to the defaultClient in ClientFactory.
https://github.com/gotify/android/blob/7432960c0ba574ad0b8c13fb9f1dbba7f8e85153/app/src/main/java/com/github/gotify/api/ClientFactory.java#L43-L49 

This is how I refactored the above method (probably the _if_ are not needed because it should create a new client with no headers in the previous code):
```java
private static ApiClient defaultClient(
        String[] authentications, String baseUrl, SSLSettings sslSettings) {
    ApiClient client = new ApiClient(authentications);
    CertUtils.applySslSettings(client.getOkBuilder(), sslSettings);
    client.getAdapterBuilder().baseUrl(baseUrl);
    client.getOkBuilder().addInterceptor((chain) -> {
        Request request = chain.request();
        if (request.header("CF-Access-Client-Id") == null) {
            request = request.newBuilder()
                    .addHeader("CF-Access-Client-Id", "my-client-id")
                    .build();
        }
        if (request.header("CF-Access-Client-Secret") == null) {
            request = request.newBuilder()
                    .addHeader("CF-Access-Client-Secret", "my-client-secret")
                    .build();
        }
        return chain.proceed(request);
    });
    return client;
}
```

What stopped me from implementing the feature is that it has to be generalized and abstract. That means the possibility to add any type of header and an arbitrary number. I think this feature should be added in the [advanced_settings_dialog](https://github.com/gotify/android/blob/7432960c0ba574ad0b8c13fb9f1dbba7f8e85153/app/src/main/res/layout/advanced_settings_dialog.xml) because in some cases, as Cloudflare's Access, it needs the headers for every request.

## Setup Cloudflare to try it
If you want to test it on Cloudflare with Service Token, there are a few important steps to do before being able to use it, otherwise, the client will not be able to connect to the server.
Let's suppose the domain is **gotify.domain.com**

#### Cloudflare's dashboard setup
* After selecting the domain, a WAF rule (Security -> WAF) has to be added to the hostname **gotify.domain.com** to bypass the JS Challenge and any other client-side verification. If this rule is not added, the client will not be able to connect. In my case, I added only to bypass _Security Level_ for the hostname and it worked.
* In _Network_ the option _WebSockets_ has to be enabled.

#### Cloudflare's Zero Trust dashboard setup
* You have to create a _Service Token_, it will ask for a name for it, let's suppose its name is **st_gotify**.
* You have to add a self-hosted _Application_. Two policies will be needed for that application:
  * A policy which will allow using the Service Token as an authentication method: select as _Action_ the value _Service Auth_ and create an _Include_ rule which has as _Selector_ the value _Service Token_, and as _Value_ the value **st_gotify**.
  * The second policy will allow the Service Token to access the application: select as _Action_ the value _Allow_, create an _Include_ rule which has as _Selector_ the value _Everyone_ and as _Value_ the value _Everyone_. Create another _Require_ rule which has as _Selector_ _Service Token_ and as _Value_ the value **st_gotify**.

#### Notes
* In the second policy I usually configure my policies as that one, adding an Include to Everyone and then a set of Require rules, the main reason is to avoid spam. If you set up an Allow policy and add only an Include rule on a specific email, only that email will be able to authenticate, but if someone tries to use another email, you will get an email with the OTP code if you have an _all-catch_ rule in your email server. Even if the other email types the OPT, it will be denied access, but the issue is that someone can just spam your email by trying different emails, and that can be annoying.
* The easier way to set up gotify and the tunnel is to use Docker. It requires almost no configuration. Something important is to put gotify and the tunnel under a _user bridge_, this will allow using _hostnames_ instead of IPs when setting the tunnel on Cloudflare. This is important because if your gotify container has an IP, it is not guaranteed that at the next restart it will be the same, while hostnames do not change because the default hostname is the container's name.

**Comment by jmattheis** [comment]
Hey, thanks for the extensive description of your problem, but it sounds like a
problem that not many will have. I'd like to keep gotify simple and only
implement stuff that is useful for the broader user-base. Sadly, I don't think
this feature fits in this category.

**Comment by CrazyWolf13** [comment]
@jmattheis noo, that would be so useful to have.

Having a secured locked down way to access to gotify would be so nice :)
