### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by jmattheis** [gotify/android#26]
Requested in https://github.com/gotify/server/issues/57#issuecomment-438812728

**Comment by sik0vny** [comment]
Definitely, dark mode is needed:)

**Comment by ktpx** [comment]
Dark mode in the android app, puhleease.  My sick eyes do not like bright lights :cry:

**Comment by sindastra** [comment]
Don't forget about a "night mode" too (pitch black). Useful for OLED screens as it saves battery.

**Comment by ktpx** [comment]
AFAIK this is a simple CSS change? whats the holdup :D
