### ISSUE TITLE
Feature request: Archive/"mark as read" notifications

### ISSUE THREAD

**Issue by nel0x** [gotify/android#260]
It would be nice if it was possible somehow mark notifications as read or "noticed". This way opening the Gotify app, you would directly see if there were any unnoticed, new events.
Right now, of course, you can see the timestamp at the top right of each message but sometimes - especially if there are multiple notifications of the same type (e.g. ssh login) in a row - it can be difficult to distinguish messages that have already been reviewed from new ones.

At the moment it's possible to delete notifications in the app by swiping left _or_ right; instead swiping left (or right ...) could check off the notification in some way.

**Comment by jmattheis** [comment]
See https://github.com/gotify/server/issues/518
