### ISSUE TITLE
UI bug: upper part of the UI not showing if the URL is too long

### ISSUE THREAD

**Issue by OB-UNISA** [gotify/android#261]
The upper part of this UI is not showing if the URL is too long.
In the images below there is an example of how it shows the UI when I use a remote URL which is a long one compared to using the local IP.

![Screenshot_20230103_093713_Gotify.jpg](https://user-images.githubusercontent.com/68842946/210324470-4b2371d3-c838-4fb1-91fb-3a41a21bc1de.jpg)

![Screenshot_20230103_094049_Gotify.jpg](https://user-images.githubusercontent.com/68842946/210324552-abed5fda-c5e3-4004-a2e1-bc83c6119d8a.jpg)

The phone is a Samsung S21 Ultra with Android 13 One UI 5.0.

**Comment by Sternagfonkel** [comment]
How would a fix for this look like? In case the url gets too long:
1. Limit the number of lines for the connection url, cut the string and add a '...' at the end if applicable.
2. Increase the height of the blue header container.
3. Remove other items in the header.
4. ...

**Comment by OB-UNISA** [comment]
> How would a fix for this look like? In case the url gets too long:
> 1. Limit the number of lines for the connection url, cut the string and add a '...' at the end if applicable.
> 2. Increase the height of the blue header container.
> 3. Remove other items in the header.
> 4. ...

The issue can occur also when the username is too long as you can see from the screenshot below.
![Screenshot_20230108_130458_Gotify.jpg](https://user-images.githubusercontent.com/68842946/211195116-567e56c5-b245-4692-93ff-cc4793bfad43.jpg)

I think a solution could be to limit the space the username and URL can have and put them in a vertical scroll view.

**Comment by cyb3rko** [comment]
@jmattheis What do you think?
Like mentioned by @Sternagfonkel you could limit the max lines to 2 and cut the rest.

I have a question about the header content: Is the username shown at the top always the same as the prefix of the URL before the @?
If that's the case you could just remove that redundant part of the URL to shorten the shown URL.

**Comment by jmattheis** [comment]
Limiting to two lines max sounds reasonable. Yeah, the username is redundant, it can be removed from the url.

**Comment by cyb3rko** [comment]
@Sternagfonkel @OB-UNISA 
What about this?  
The second textview does not contain the username anymore and both the username and the url can wrap to 2 lines and is cut at the end of the 2 lines. 

The header expands to the bottom if there are multiline textviews to not push the Gotify logo out of screen at the top.

<img src="https://user-images.githubusercontent.com/46033730/216818448-7c7f4679-c03e-4d14-92ef-ed411536b815.png" width=300>  
<img src="https://user-images.githubusercontent.com/46033730/216818452-0a60cc7c-1606-45ed-8ab3-ecf122e946f7.png" width=300>

**Comment by Sternagfonkel** [comment]
Hopefully are two lines enough. I think this is the only place where the url is displayed (correct me if I'm wrong). And it might be helpful for some users to see the full url. But not sure if this concern is real. For me, your suggestion looks fine, I would keep it :)

**Comment by cyb3rko** [comment]
You have to keep in mind I removed the username from the url field.
So the example above from @OB-UNISA would fit into a single line.  
Then there's only the username, that would be cut.

On the Pixel 6 and 7 Pro there's space for a little more than 70 characters that can be shown in the 2 lines of url view, that would be an url like the following:  
https://mygotifysubdomain.thedomain.topleveldomainwithaveryverylongname

I suppose (or rather hope) nobody would ever choose any kind of url that looks like this.  
And even if that would be cut off on a smaller screen, you can see enough of it to identify it I would say, right?

**Comment by cyb3rko** [comment]
No other opinions, time for a PR I guess.
