### ISSUE TITLE
Manually reconnect

### ISSUE THREAD

**Issue by powellnorma** [gotify/android#263]
Is there a way to manually trigger a reconnect, in order to avoid having to wait (max.) 20min? So let's say the server also can access the phone via adb/shell, is there e.g. an activity that could be launched via `am start -n` that would trigger an reconnect?

I tried `am start -S -n com.github.gotify/com.github.gotify.messages.MessagesActivity` but then no notifications are displayed. Thank you for your help!

**Comment by jmattheis** [comment]
You can force stop the app in the android app settings and the open it again.

**Comment by powellnorma** [comment]
Thank you, but I need a way to do it remotely and automatically - Is there a way?

**Comment by jmattheis** [comment]
You can probably forceStop and restart the app via adb

**Comment by powellnorma** [comment]
This is what I tried to do with `am start -S -n com.github.gotify/com.github.gotify.messages.MessagesActivity` - The `-S` force stops the application first. However I noticed that new incoming messages are not received after this. Maybe `com.github.gotify.messages.MessagesActivity` is not the right activity for "properly" starting the app?

**Comment by powellnorma** [comment]
Is it guaranteed that the app will try to reconnect after it a WLAN connection got established? Because in that case, I could trigger a WLAN reconnect, which should then trigger a gotify reconnect?

**Comment by jmattheis** [comment]
Try starting `com.github.gotify.init.InitializationActivity`. There is no guarantee, it'll wait the reconnect timeout.

**Comment by powellnorma** [comment]
This seems to work, thank you!
