### ISSUE TITLE
Use similar text on button for deleting all messages

### ISSUE THREAD

**Issue by PanderMusubi** [gotify/android#265]
The text on the button to delete all messages in teh web GUI is `DELETE ALL`

![web3](https://user-images.githubusercontent.com/198964/211314590-6b096c24-6af9-4465-8b53-80220957f523.png)

In the app it is called `Clear messages`

![app3](https://user-images.githubusercontent.com/198964/211314604-adef099d-fed8-45e4-9ef6-8873315aa3a8.png)

Please rename the text on the button in the app to `Delete all messages` e.g. Perhaps it is already changed in commits since the last release, but I could not find it in the source or the commits.

**Comment by jmattheis** [comment]
I don't think this is much of an issue, but I'm open to accept PRs for this.

**Comment by PanderMusubi** [comment]
I cannot find via grep where in the source this is set. Can you point me in the direction?

**Comment by jmattheis** [comment]
It's in the strings.xml
```
$ rg 'Clear messages'
app/src/main/res/values/strings.xml
26:    <string name="delete_all">Clear messages</string>
```

**Comment by PanderMusubi** [comment]
Done in https://github.com/gotify/android/pull/267

**Comment by PanderMusubi** [comment]
Is in https://github.com/gotify/android/pull/268 now
