### ISSUE TITLE
Add circular crop to application icons

### ISSUE THREAD

**Issue by PanderMusubi** [gotify/android#266]
Add circular cutout in all places in the app where an icon is used (menu, messages and notification), similarly to the web GUI does.

The web GUI shows

![web](https://user-images.githubusercontent.com/198964/211315370-1733508b-d07f-4f11-a70c-72587dc08df3.png)

And the app shows

![app](https://user-images.githubusercontent.com/198964/211315394-99020b50-5dc7-409a-9a12-941b618b51a8.png)

and

![app2](https://user-images.githubusercontent.com/198964/211315430-7320db9a-66fe-451f-8e50-653d89bc419e.png)

**Comment by jmattheis** [comment]
Images should be squares. The only inconsistency is the display of the applications page.

**Comment by PanderMusubi** [comment]
Shall I make a PR so the server shows squares also in the application overview?

**Comment by PanderMusubi** [comment]
See https://github.com/gotify/server/issues/539
