### ISSUE TITLE
Error 403 "/version"

### ISSUE THREAD

**Issue by STR3IKERKRYPTON** [gotify/android#269]
I'm running gotify ver. 2.2.4 in a docker container and I'm using the android client. 
If I'm accessing gotify over the webUI everything works fine. But if I use the android client I get the following error:
Request to gotify.domain.com/version  failed with status code 403

And there is nothing interesting to see in the container logs.
The android client is on the newest version.

Has anyone had this problem?

**Comment by jmattheis** [comment]
Please post the gotify/server and android logs after you've tried to login.

**Comment by STR3IKERKRYPTON** [comment]
gotify/server:

[GIN] 2023/01/24 - 13:38:35 | 200 |      43.073µs |       127.0.0.1 | GET      "/health"
[GIN] 2023/01/24 - 13:39:05 | 200 |      85.914µs |       127.0.0.1 | GET      "/health"
[GIN] 2023/01/24 - 13:39:35 | 200 |       47.53µs |       127.0.0.1 | GET      "/health"
[GIN] 2023/01/24 - 13:40:05 | 200 |      46.479µs |       127.0.0.1 | GET      "/health"
[GIN] 2023/01/24 - 13:40:35 | 200 |      40.497µs |       127.0.0.1 | GET      "/health"
[GIN] 2023/01/24 - 13:41:05 | 200 |      41.641µs |       127.0.0.1 | GET      "/health"
[GIN] 2023/01/24 - 13:41:35 | 200 |      41.099µs |       127.0.0.1 | GET      "/health"
[GIN] 2023/01/24 - 13:42:05 | 200 |      59.505µs |       127.0.0.1 | GET      "/health"
[GIN] 2023/01/24 - 13:42:35 | 200 |      42.041µs |       127.0.0.1 | GET      "/health"
[GIN] 2023/01/24 - 13:43:05 | 200 |      51.198µs |       127.0.0.1 | GET      "/health"


Android client:

2023-01-24T12:44:04.137Z INFO: Entering LogsActivity
2023-01-24T12:44:03.219Z ERROR: Error while api call
Code(403) Response: <!DOCTYPE html>
<html lang="en-US">
<head>
<title>Just a moment...</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="I
at com.github.gotify.api.Callback$RetrofitCallback.onResponse(Callback.java:74)
at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:71)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:233)
at android.os.Looper.loop(Looper.java:344)
at android.app.ActivityThread.main(ActivityThread.java:8212)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

**Comment by jmattheis** [comment]
Gotify isn't receiving the request, you probably have something in front of gotify that is intercepting the request. Maybe cloudflare or something similar.

**Comment by STR3IKERKRYPTON** [comment]
Client -> Cloudflare -> ReverseProxy -> gotify/server

That was my first thought as well, since other services outside of the browser also cause problems. Haven't found anything on cloudflare though.

**Comment by jmattheis** [comment]
The gotify/android client probably gets a captcha or some other means to check if this request is valid. gotify/android doesn't expect this and fails because cloudflare returns 403 Forbidden.

**Comment by STR3IKERKRYPTON** [comment]
The strange thing here is that it all worked before. I opened the android app yesterday and noticed that I can no longer connect and I haven't changed anything in cloudflare. I know that cloudflare got their own captcha but I've never activated it.

**Comment by STR3IKERKRYPTON** [comment]
In addition, it should be mentioned that the error shows up before I enter the login credentials.

**Comment by jmattheis** [comment]
> In addition, it should be mentioned that the error shows up before I enter the login credentials.

After entering the url gotify checks the connection by requesting the version of gotify. This request should always succeed as there is no authentication on this endpoint. Hence, it was used for this.

> The strange thing here is that it all worked before.
> It also never shows up if I open my services in the browser.

Well, you're using cloudflare, and cloudflare has probably detected your phone as bot and denied access. It could be related to several things, like changing IP addresses from your phone, or having a connection open for a long time.

Anyway, this is not the right place to debug your specific setup, this is unrelated to gotify as you've a service between gotify and the gotify client that denies access.

**Comment by STR3IKERKRYPTON** [comment]
I found the problem. The whole thing is due to the VPN running on my smartphone. Thank you for your help 👍
