### ISSUE TITLE
When deleting the first message and undoing the action, the view should be scrolled up to show to the user that the message was restored

### ISSUE THREAD

**Issue by OB-UNISA** [gotify/android#280]
If I delete the first message and undo the action, the UI doesn't show that the message was restored, I have to manually scroll up as is shown in the first video. 

https://user-images.githubusercontent.com/68842946/219216738-113defa7-9082-4580-853f-376a16285675.mp4

The issue can pile up when deleting and restoring several messages as shown in the second video.

https://user-images.githubusercontent.com/68842946/219217318-482db76a-ef45-43e9-88a8-dd9e1a555f20.mp4

I'm pointing this out because if a message which is not the first one is deleted and restored, the user can see it as shown in the third video and this behaviour would be expected in the above case too.

https://user-images.githubusercontent.com/68842946/219216974-12664a6f-9d80-4cf3-bc47-d119b547ca4f.mp4

**Comment by OB-UNISA** [comment]
I noticed that the issue happens also when deleting and restoring the last message.

https://user-images.githubusercontent.com/68842946/219222869-b3acb84b-6984-449e-8a20-43dc16af2c9a.mp4

**Comment by jmattheis** [comment]
I think the current behavior is fine. The view shouldn't jump when you delete or undo the deletion of a message. The only outlier is, if the message will be inserted between messages you're currently seeing.
