### ISSUE TITLE
Feature Request: Make it possible to disable certain app channels

### ISSUE THREAD

**Issue by pafade89** [gotify/android#290]
Hi together,

it would be useful to make it possible to disable single app channels (checkbox) in the android app. So you get only activated app notifications, but it is furthermore possible to see notifications of the channel by clicking on it.

Cheers P

**Comment by jmattheis** [comment]
You can enable "Separate app notification channels" inside the settings and then disable notifications for a specific application in the android notification settings for the gotify app.
