### ISSUE TITLE
Wear os companion app?

### ISSUE THREAD

**Issue by baudneo** [gotify/android#295]
I know this is a huge ask but I thought I would throw it out there anyways.

Pushover and other similar apps don't have a wear os companion app to receive notifications on a watch. Would be absolutely amazing to get Gotify notifications on my watch.

Tha ka for your work!

**Comment by jmattheis** [comment]
I'm not sure if that's really needed by the broader user base of gotify. Please :+1: this issue, if it's something you'd like.

**Comment by baudneo** [comment]
For others that stumble upon this. You can buy an app called "Bubble cloud" for your wear os watch by DynaLogix. It has other (paid) plugins that can get you the Gotify (and all other) notifications on your watch for under $10 USD.

It may need Tasker as well, I am uncertain. I already have Tasker so couldn't test without it.

Very nice!

Again, thanks for your work on Gotify!
