### ISSUE TITLE
Login screen bugged into status bar

### ISSUE THREAD

**Issue by cyb3rko** [gotify/android#297]
It seems one of the last commits led to a bug.  
Currently the login screen is bugged into the status bar, so the Logs button and the logo disappears into the top.

<img src="https://github.com/gotify/android/assets/46033730/50542618-436b-4ebb-b298-5e82dbd22027" width="400"/>

**Comment by jmattheis** [comment]
I can reproduce it, likely introduced by https://github.com/gotify/android/pull/292
