### ISSUE TITLE
Do not show permanent "Connected" notification, only show "Disconnected" notification

### ISSUE THREAD

**Issue by gratefulUser1** [gotify/android#308]
On my android mobile, when connect to the server, I get a permanent "Connected" notification/icon which I cannot remove. It would be better to not have this notification/icon (takes up space and cannot be distinguished from disconnected notification). It would be good to only show this permanent notification/icon, when the connection to the sever is disconnected. At least one could make the the "Connected" notification optional in the settings.

EDIT: I know, I can change the importance of the "Connected" notification in Android, however, I want to keep the importance but only show the notification when "Disconnected".

Side note: Thanks a lot to all contributors for this great work and app and for your efforts. It's a really great and helpful piece of software!

**Comment by jmattheis** [comment]
The permananent / foreground notification is a requirement from android. It ensures that the gotify background service has a high priority and therefore won't be killed as fast as other services.

**Comment by gratefulUser1** [comment]
OK, understood, thank you. Means one either has to live with the permanent notification or is not notified when the connection is lost, right?
