### ISSUE TITLE
Cleartext communication not allowed on Android 9.0/Pie

### ISSUE THREAD

**Issue by MisguidedEmails** [gotify/android#31]
Cleartext communication isn't allowed on Android Pie by default, so currently at least an SSL enabled Gotify server must be used.

Error message in adblog: `Caused by: java.net.UnknownServiceException: CLEARTEXT communication to <IP> not permitted by network security policy`

Tested by connecting to a default Gotify server.

**Comment by MisguidedEmails** [comment]
I feel like as long as there is a warning and you confirm that it's insecure it should be fine (something similar to the "disable ssl validation" checkbox). But if not the error should probably change to mention that cleartext isn't supported on Pie instead of the "status code 0" message

**Comment by jmattheis** [comment]
Your idea with the confirmation dialog sounds good.
