### ISSUE TITLE
Crashes when unable to connect to server for a long period of time

### ISSUE THREAD

**Issue by Jacksaur** [gotify/android#316]
Been using Gotify for a short while now, and at home, it works absolutely perfectly. My phone (Xiaomi Pocophone F1) always kills it overnight, despite following the provided instructions on DontKillMyApp, but other than that it stays alive and provides notifications just fine through the day.

Problem is, I currently have no external access to my server, so when I leave for work I'm left without a connection for extended periods of time. Gotify recognizes this, and the Permanent Notification changes to a reconnecting message with gradually increasing delay. After a long while, when the notification has hit 17 or 20 minutes to the next attempt, Gotify seems to crash entirely. Trying to open the app will either have it freeze on the logo and never open the "Oops" dialogue, or it'll be effectively invisible and just freeze my phone's screen until I switch apps again.

Even without opening it, the app appears to be entirely dead. Once I get home again, it'll never reconnect to my server, no matter how long I wait. This could potentially be related to my phone auto killing it still, but the permanent notification does stick around so I'm not sure.

I tried the Logs section to get an idea of the exact timing but that doesn't seem to track when the app isn't fully open. Anything else I can provide to further help diagnose the issue here?

**Comment by jmattheis** [comment]
Your issue could be related to #311 but without logs it difficult to say. In #317 I've improved the logging, so that it'll persist between restarts.

Let's wait until both the changes are merged into master and then rechecked if the issue still exists for you.

**Comment by Jacksaur** [comment]
I was finally able to stop my phone aggressively killing apps by using Universal Android Debloater to disable the "miui.powerkeeper" service. So that'll now rule out the auto kill as the cause.

I'll test things again as soon as those patches are merged.  
I assume I'd just have to open the Gotify logs in the morning, go to work, see if the app is still functional when I get home again, and then restart and send the logs over if not?

**Comment by jmattheis** [comment]
Yeah, if it doesn't work the android log until the crash time and the gotify/server log would be helpful. 

Version 2.7.1 includes both changes, it'll be available shortly on Google Play and in some days on f-droid.

**Comment by jmattheis** [comment]
Feel free to open if the problem occurs for you.
