### ISSUE TITLE
Foreground service type of Gotify app

### ISSUE THREAD

**Issue by cyb3rko** [gotify/android#324]
I'm currently porting the app to sdk 34 and updating gradle and other dependencies.  
A new requirement of targeting SDK level 34 is to define a foreground service type for the web socket service.

Which one do you think fits the best?  
https://developer.android.com/about/versions/14/changes/fgs-types-required

**Comment by jmattheis** [comment]
"Data sync" sounds reasonable, but this is already deprecated. So I'd say we use "Special use" as type and describe the long running websocket service there.

**Comment by cyb3rko** [comment]
Would you like to define the "explanation for special use"?

**Comment by jmattheis** [comment]
sure, I'll come up with something when a PR is open.
