### ISSUE TITLE
feature request: local network

### ISSUE THREAD

**Issue by MoontoC** [gotify/android#328]
like home assistant android app and server

![Screenshot_20211017-134754_Home Assistant](https://github.com/gotify/android/assets/840504/337aa342-b438-4906-ad3c-436c0be935dd)

![屏幕截图 2023-12-01 234540](https://github.com/gotify/android/assets/840504/13bc781f-3b16-44d4-a330-3578dc335118)

**Comment by jmattheis** [comment]
This seems like a rare edge-case to me, it can probably be solved without having the android application to know two ips. As is I don't think I want to support this.
