### ISSUE TITLE
Feature request: delete applications UI

### ISSUE THREAD

**Issue by d03j** [gotify/android#329]
Can we add an option to disable "delete applications" and/or ask for confirmation before deleting applications and/or moving it somewhere else in the UI?

With Delete Applications and Delete All Messages being next to each other, it is quite easy to delete an application instead of all messages. Deleting all messages by accident is not ideal but deleting an app is a PITA: it can cause scripts to crash, requires you to create new tokens and editing associated scripts.

**Comment by cyb3rko** [comment]
Maybe we should implement something similar like #296

**Comment by d03j** [comment]
FWIW, I think it is probably worth for the confirmations to be able to be enabled/disabled separately (app/all messages).

In my case I'd only turn it on for the app deletion, otherwise I'd end up getting used to clicking delete all messages / yes so often that whenever I clicked delete app by mistake, I'd just click yes straight away. :)

**Comment by cyb3rko** [comment]
Maybe that's a bit overkill. Keeping it simple was always the thought with Gotify.  
@jmattheis It's your turn ;)

**Comment by jmattheis** [comment]
Yeah, having this configurable seems to overkill for me but adding the confirmation dialog for deleting the application is a good addition.

**Comment by d03j** [comment]
> Maybe that's a bit overkill. Keeping it simple was always the motto of Gotify. @jmattheis It's your turn ;)

From a UX and simplicity perspective I think separating the "delete all messages" from "delete all apps" is better than adding a confirmation dialogue. Putting "delete all apps" on the sidebar menu along with Push Messages, etc, or maybe even within settings feels more aligned to the web app's approach and more logical - deleting an app is more like a "settings" type of action.

In addition, if you separate the two deletes, I don't see the point of adding a confirmation dialogue for delete all messages, as you'd have to be pretty intentional to click on it. The only way to get to it is by clicking on the top right hand corner ellipse and there is no way to confuse it with deleting a single message. :)

Having said that, I'll take what I can get :) I'm very thankful for the app as it is!

**Comment by cyb3rko** [comment]
I've quickly wanted to fix this when I realized, that we already have it in place:  
https://github.com/gotify/android/blob/07f931d3305a4b5ee9afacbfcde464efb2281e56/app/src/main/kotlin/com/github/gotify/messages/MessagesActivity.kt#L530-L537

I would call this dialog an additional confirmation before deleting. I think it's sufficient

**Comment by jmattheis** [comment]
I agree. I'll close this issue as this is good enough IMO.
