### ISSUE TITLE
Outdated screenshots + preview

### ISSUE THREAD

**Issue by cyb3rko** [gotify/android#330]
I've noted that the screenshots on Google Play Store, F-Droid and the preview in the README are pretty outdated and old.  
Are you interested in updating them?  
I could help

**Comment by jmattheis** [comment]
yes, especially the GIF in the README is pretty old. Feel free to update them, here are the images I've used previously: [1](https://github.com/gotify/android/assets/14895212/a061a900-ec8c-4344-a4b4-d39b87719765) [2](https://github.com/gotify/android/assets/14895212/907257b6-d50d-4c6b-aeb3-78f5db7bd807) [2](https://github.com/gotify/android/assets/14895212/bfab1066-c29c-4540-b7d4-a3b57ad2219f)

**Comment by cyb3rko** [comment]
I could instead choose their respective current icon, as these images are of some age as well :)

**Comment by jmattheis** [comment]
As long as they are free to use, feel free to use different ones. Having "real" logos may require attribution or some trademark notice which I rather not have on these images. My linked images are from pixabay.

**Comment by cyb3rko** [comment]
Got it, then I will use your images

**Comment by cyb3rko** [comment]
<img src="https://github.com/gotify/android/assets/46033730/bad21a01-4228-4788-b8d6-e55e08b93fd4" width="600"/>

Additionally the F-Droid badge is broken, we can use this as an alternative (https://fdroid.gitlab.io/artwork/badge/get-it-on.png), and the dividers cut through the preview gif somehow.

**Comment by cyb3rko** [comment]
Like this?

https://cdn.cyb3rko.de/Apps/Gotify/new.gif

**Comment by jmattheis** [comment]
Yes, looks good!
