### ISSUE TITLE
Snapshot not appearing on phone

### ISSUE THREAD

**Issue by slopsjon** [gotify/android#331]
`#!/bin/bash
TITLE="Motion"
MESSAGE="(https://ha.home.org/api/hassio_ingress/kMp6bA8Lxms9l9tZoWRsjsysV__bT0PmhU7z0E2Exkg/picture/1/current/)"
PRIORITY=10
URL="https://gotify.home.org/message?token=AQ97fzESIaMHLNP"

curl -s -S --data '{"message": "'"${MESSAGE}"'", "title": "'"${TITLE}"'", "priority":'"${PRIORITY}"', "extras": {"client::display": {"conte>
`
EDIT: The message line above has ! [  ] before the (https It keeps getting edited out when I post.
I'm using the above script to send a snapshot to Gotify. The snapshot is viewable in the web interface of my docker container, but all I get in the phone app is the title and an image saying OBJ. Any ideas?

**Comment by jmattheis** [comment]
Is the URL of the image accessible without authentication?

**Comment by slopsjon** [comment]
Yes, I don't have to authenticate when view it on the web page.

**Comment by slopsjon** [comment]
When I try private tab, it doesn't display the image.
What it shows in the app is a tiny square with the letters OBJ inside, which I think means Object. 
I tried coping the log on the phone and it only returned a log upto the end of last year. So deleted the log, sent an image again and now when I try view the log to copy it the app locks up. I tried reboot the phone but just doesn't like me going into the log. The app slows down and then locks up when I try and copy it even if it's empty.

**Comment by slopsjon** [comment]
I have sorted this out now. Basically what I was sending the App, the App couldn't resolve into an image but the browser could. So I now send it a URL pointing to a png file (which what it said on the website). I've had to use nodered to convert the base64 object from MQTT to a PNG file and then access it from the nodered dashboard UI URL. Thanks for your help.
