### ISSUE TITLE
Gotify is not responding

### ISSUE THREAD

**Issue by Circenn5130** [gotify/android#338]
I'm having a newly developed issue with the android app where upon opening, the UI is black and I'm unable to do anything. Shortly afterwards an error comes up with "Gotify isn't responding: Close app | Wait". 
I'm not able to retrieve any logs from the app due to this. If there's another way to pull them from the phone let me know. 

- The app is definitely establishing a connection despite this issue, sometimes I get a notification from it, and the unread notification badge counter reflects unread notifications accurately. I either haven't found a way to debug the server, or there isn't an option for it, so its logs aren't useful in troubleshooting. 
- Tried uninstalling/reinstalling from Google Play and the apk
![image](https://github.com/gotify/android/assets/20010643/58831d33-25ee-42a0-94cb-373025cb4acf)

```
Samsung
Galaxy S23 Ultra

Hardware
Qualcomm® Snapdragon™ 8 Gen 2 for Galaxy
Hardware: SM8550
Cores: 8
CPU:
3 x Cortex-A510
2 x Cortex-A715
2 x Cortex-A710
1 x Cortex-X3
Process: 4 nm
Frequencies:
307 MHz - 2016 MHz
499 MHz - 2803 MHz
499 MHz - 2803 MHz
595 MHz - 3360 MHz
Governor: walt

GRAPHICS
Vendor: Qualcomm
GPU: Adreno (TM) 740
OpenGL: OpenGL ES 3.2 V@0676.42 (GIT@7b26bdd942, Iab69c31769, 1693222181) (Date:08/28/23)
Max frequency: 719 MHz
Resolution: 3088 x 1440
Screen density: 376.90802 ppi
Screen size (estimated): 6.78 in / 172 mm

RAM
RAM size: 8 GB
Type: LPDDR5x 4200MHz
Channels: 16-bit Quad channel

DEVICE
Model: SM-S918U
Codename: dm3q
Manufacturer: samsung
Manufacturing date: Feb 16, 2023

System
Android Version: Android 14 (U)
Build: UP1A.231005.007.S918USQS2BXBD
ROM base: S918USQS2BXBD
Security patch: Mar 1, 2024
Architecture: aarch64 (64-bit)
Supported ABIs: arm64-v8a armeabi-v7a armeabi
Kernel: 5.15.94-android13-8-27763874-abS918USQS2BXBD #1 SMP PREEMPT Wed Feb 28 09:16:59 UTC 2024 aarch64 Toybox
```

**Comment by jmattheis** [comment]
There is no crash report for your device reported to the google play console. I'm not sure what the preconditions are when crash reports are uploaded to google.

If you have android dev tools installed, you can enable usb debugging and listen to crash logs with
```
adb logcat -b crash
```
After starting the command you'd have to trigger the crash.

**Comment by Circenn5130** [comment]
So I'd just finished moving my Gotify instance's DB from SQLLite to Postgres, and I'd reinstalled the app via the Playstore (the last time I'd reinstalled it from troubleshooting, I used the APK from its repo), and now it's connecting fine (of course lol). Should the behavior manifest again I'm all setup to provide an output from logcat. 

Thank you so much for your prompt assistance and time.
