### ISSUE TITLE
Feature request: Allow per-app notification sounds

### ISSUE THREAD

**Issue by diamondburned** [gotify/android#340]
Currently, all app notifications on Android use the same default sound unless the user manually customizes sounds for specific notification channels (https://github.com/gotify/android/issues/18#issuecomment-2027980969). This customization only applies to the selected channel and doesn't provide app-specific sound control.

This issue proposes a feature that would allow users to upload custom sound files through the web portal for a specific app. These custom sounds would then be used for all notifications coming from those apps, overriding the default Android sound.

However, I'm unsure if this feature is technically feasible. While Gotify can (probably?) set a default sound for a notification channel, this approach faces the same limitations mentioned above. Is it possible to dynamically assign unique default sounds to individual notifications using Android's API?

**Comment by jmattheis** [comment]
In the app you can enable "Separate app notification channels" in the settings. This will create a notification channel for each application and allow you to create custom sounds for different applications.

I don't think it's worth implementing server side notification sounds, as not many users need this.
