### ISSUE TITLE
Feature request: change links colour in dark mode 

### ISSUE THREAD

**Issue by MyWay** [gotify/android#341]
Hi, I'm proposing just a small enhancement. Blue text links on dark mode are barely readable, could you please use a lighter colour? Thanks.

**Comment by jmattheis** [comment]
Yes, the colors are currently inconsistent between markdown links and text/plain links. (orange = markdown, blue = plain)

![image](https://github.com/gotify/android/assets/14895212/284fa129-3897-451b-93c2-144aad05f6ef)
