### ISSUE TITLE
Feature request:  alert and panic mode

### ISSUE THREAD

**Issue by zolonn** [gotify/android#347]
Feature request

As I use (and hopefully not only me) the Gotify to notify me about events in my infrastructure (Zabbix and Kuma notifications), I would like to ask for following feature:

- message with priority 7: medium alert mode - should do some sound even if the mobile is in silent mode
- message with priority 8: high alert mode - should do some sound even if the mobile is in silent mode and/or in DND status
- message with priority 9: panic mode - should do some continuous sound (like alarm clock) till confirmed, even if the mobile is in silent mode and/or in DND status

/BR
zolonn

**Comment by jmattheis** [comment]
It's requested in the linked issue.
