### ISSUE TITLE
What relative paths of Gotify endpoint does the App connect to?

### ISSUE THREAD

**Issue by spinnaker1** [gotify/android#349]
Hello,

can someone tell me what paths of the Gotify endpoint, the Android App connect to and requires to work?

Does it connect to normal web login:
https://www.mygotifyinstance.tld/#/login/ ?

OR only via API endpoints? (https://gotify.net/api-docs#/)
If so, what relative paths exactly?

I'm asking because I want to restrict access to my Gotify endpoint and only expose the API paths that are essentialy needed by the App. And I don't understand enough of the code to read it.

**Comment by jmattheis** [comment]
Similar to the webui the android app uses the API endpoints. I'd say the app could use all api endpoints in the future, currently it only uses most endpoints. I don't think you get much benefit from blacklisting unused endpoints.
