### ISSUE TITLE
about notification

### ISSUE THREAD

**Issue by Pr0xy970** [gotify/android#351]
Can I block this notification? 
![Screenshot_20240610_040813_com huawei android launcher_edit_26061184664771](https://github.com/gotify/android/assets/62409461/eaced331-2959-4e3c-a995-0e4c1c79e75f)
Or use different channels for the two types of notifications?
![Screenshot_20240610_041500_com huawei systemmanager](https://github.com/gotify/android/assets/62409461/fd5bba14-1c42-4637-bbba-557ff68c95f9)

**Comment by jmattheis** [comment]
See https://github.com/gotify/android?tab=readme-ov-file#minimize-the-gotify-foreground-notification
