### ISSUE TITLE
Feature: Allow Redirects

### ISSUE THREAD

**Issue by bun-dev** [gotify/android#352]
Hello! I want to preface this by saying I am absolutely loving the android app. A problem I found is that redirects don't work in the app. My gotify server is behind a cloudflare tunnel which redirects to an access page that requires a code in order to access the url. The only way to make this work is if I setup a policy in cloudflare to bypass this authentication. This means the service is exposed with only basic login auth. I believe this would also be a problem if the service was using authelia(2fa service) since that also redirects to a login page. Is there any way around this? thanks
![ss 06-13-24](https://github.com/gotify/android/assets/34141271/8a96ca70-5a27-448e-b488-ca09db082f9c)

**Comment by jmattheis** [comment]
Authelia or anything that redirects is not supported by the android app. There are some issues on the gotify/server repo about this, but currently there is no way to work around this.

**Comment by bun-dev** [comment]
I see, figured I'd ask to make sure, thanks
