### ISSUE TITLE
Release plans?

### ISSUE THREAD

**Issue by PrakashW94** [gotify/android#354]
Hi, firstly thanks for all your work on gotify!

Just wanted to ask about your plans regarding cutting a release? I've love to be able to utilise some of the newer features that have been merged recently. 

I understand I could build the APK myself but I figure there are likely to be others who are also in my position.

**Comment by jmattheis** [comment]
I'll create a new release after https://github.com/gotify/android/pull/353 is merged.

**Comment by PrakashW94** [comment]
Hi, Is there any update on cutting a new release? I can see the PR you've linked has now been merged.
