### ISSUE TITLE
Feature: Snooze Notifications

### ISSUE THREAD

**Issue by bun-dev** [gotify/android#355]
I'd love for a feature that allows you to disable notifications from apps for a specific amount of time. For example, When I'm home and working in the yard, I will get flooded with notifications from my camera. Ring doorbell has this feature and it works great

**Comment by jmattheis** [comment]
You can enable "Separate app notification channels" in the settings, then you can mute gotify apps in the native android settings. You have to re-enable it when you want to receive notifications again.
