### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by Kami-no** [gotify/android#36]
Is there a way to set a custom sound?

PS: btw I've no sound notifications from app at all...

**Comment by jmattheis** [comment]
@Kami-no Which android version do you have?

**Comment by Kami-no** [comment]
Android 8.1.0 LineageOS 15.1
Suppose it's related to wrong notification types:
https://yadi.sk/i/KiMwsyFVaW08Kg

**Comment by Kami-no** [comment]
Oh, I see.
But is there a way to set a custom sound? I'd like to know that it's gotify and not some notification from reddit with default system sound....

**Comment by Kami-no** [comment]
Also wouldn't it be more informative to know in lock screen that you have notifications and not permanent info about where gotify connected to (again about notification types)?

**Comment by jmattheis** [comment]
> But is there a way to set a custom sound? I'd like to know that it's gotify and not some notification from reddit with default system sound....

You can set a custom notification sound in the android notification settings.

* Settings -> Apps -> Gotify
* Click Notifications
* Select f.ex. the "High priority messages"-Entry
* Select a different sound in the advanced menu.

> Also wouldn't it be more informative to know in lock screen that you have notifications

Notifications with higher priorities are shown on the lock screen.

> permanent info about where gotify connected

This info on the lock screen should be disabled in version 2.0.4 which was released yesterday on f-droid.
To make the connected notification even less intrusive, see https://github.com/gotify/android#minimize-the-gotify-foreground-notification

**Comment by Kami-no** [comment]
Great! Never knew android has such features now. Thank you. Waiting for new version at Google Play

**Comment by jmattheis** [comment]
@Kami-no No problem Google Play should already have the new version, https://github.com/gotify/android#minimize-the-gotify-foreground-notification should also remove the connected notification from the lock screen.
