### ISSUE TITLE
Functional Recommendations

### ISSUE THREAD

**Issue by wxyShine** [gotify/android#361]
![c0738eada9ca7415b6f5c2030831e56](https://github.com/gotify/android/assets/42802152/44cdb0e2-4d73-4f53-ae2c-f3d74002904d)
This is  https://github.com/pppscn/SmsForwarder

Are you considering adding this function like this software?

**Comment by jmattheis** [comment]
![image](https://github.com/gotify/android/assets/14895212/f32012a5-0137-45e7-b90b-fa8cceac6a02)
