### ISSUE TITLE
inline image in markdown are not rendred anymore since last version

### ISSUE THREAD

**Issue by FabienZouaoui** [gotify/android#362]
Hi,

First of all, a lot of thanks for this app and all the great stuff on it !

Since the last version (2.8.0) inline image in markdown message are not rendered anymore in android app. Maybe, Maybe this can be linked to #356 .
Images are correctly rendered in gotify's webui.

Please have a look to this log (I'm really sorry, I can only provide a screenshot, my app is freezing when I try to show logs)
https://imgur.com/a/ODQ173R

**Comment by jmattheis** [comment]
Good catch!
