### ISSUE TITLE
Feedback from Playstore Reviews

### ISSUE THREAD

**Issue by jmattheis** [gotify/android#365]
> Reverted to a previous version. For some reason the newest one won't update date times.

**Comment by tamr** [comment]
> Do you mean the relative times besides the message title? I've reproduced that relative time doesn't update when the app is already running and is re-opened.

Yes, that's the only issue.

**Comment by jmattheis** [comment]
@tmar Thanks, the fix will be included in the next release.

**Comment by tamr** [comment]
Doh, not sure if this related to a previous issue, but I just noticed that notifications with high priorities are not vibrating. Reverted back — working, updated — not working anymore. Can anyone test this?

**Comment by jmattheis** [comment]
@tamr For me it does work, could you show your notification settings for high prio messages, e.g.:
![image](https://github.com/user-attachments/assets/c8dccb0a-1ef5-4b75-b0af-b2b8868d18e6)

What device and android version do you currently have?

**Comment by tamr** [comment]
Doh, checked it once again, indeed, it works. No idea what happened, probably pcapdroid messed something up.
