### ISSUE TITLE
Title font too large

### ISSUE THREAD

**Issue by wahlis** [gotify/android#37]
If I set the font size to medium or large on my Xiaomi (MIUI) phone only the top part of the title text is displayed. The lower part gets overwritten by the message body

**Comment by sik0vny** [comment]
I agree. Its too big. I would say that the message is more important than title. At least for me. So it would be nice to be able to set a fonts for title and message (in preferences).

**Comment by jmattheis** [comment]
Fixed via #54 & #56.
