### ISSUE TITLE
Notifications on Android TV

### ISSUE THREAD

**Issue by fredericdepuydt** [gotify/android#370]
HI,

I've installed Gotify on my android TV (via F-Droid), the notifications are correctly arriving and being showed in the message overview. But there's no notification bubble appearing, nor is the notification present in the android notification list.

I've already checked the following:
- App has all the permissions it might require
- App is allowed to send notifications

I have not found any documentation on how to setup Gotify on Android TV?
The notification behavior might be deviating from normal Android devices?

I've did find a feature request for an Android TV app, which was rejected: https://github.com/gotify/android/issues/231

Although it might require less effort, as it's already installable without issue.
Only the notification behavior might need to be altered to get this working?

This was tested on Android TV OS 12.

Kind regards,
Frederic Depuydt

**Comment by jmattheis** [comment]
The standard android notification system isn't supported on android tv. so this would require something exclusively developed for android tv. I don't think this is worth supporting for probably very small userbase that would use gotify on android tv.
