### ISSUE TITLE
Feature request: Number of notification per app

### ISSUE THREAD

**Issue by lazerleif** [gotify/android#371]
It would be nice to see how many messages there is per app in the app list. 

Example:
![Screenshot_20240830-135952_Gotify_1](https://github.com/user-attachments/assets/239677f8-c5cf-40b6-bc3b-066a0cd9e3d5)

**Comment by cyb3rko** [comment]
Duplicate of #313, isn't it?

**Comment by lazerleif** [comment]
Yes it is! I will close this one
