### ISSUE TITLE
[Bugs] Unable to complete background notifications on Xiaomi Hyper OS

### ISSUE THREAD

**Issue by rikonaka** [gotify/android#376]
Thanks a lot to all the developers, gotify worked perfectly on my other phones (like LineageOS .etc), but when I tried to accomplish something similar on Xiaomi's Hyper OS (previously known as MIUI), I found that gotify can't implement notifications in the background.

I turned on all permissions for the app, including the self-launch permission, turned on all displays for notifications, but when I close gotify (gotify app still shows `Connected` in the notification bar), I can't receive any messages.

But when I keep the app open and haven't deleted it in task manager (swipe to dismiss), everything is fine with receiving messages.

Thanks again for all the work, and it would be great to fix this bug! 😘😘😘

[gotify.log](https://github.com/user-attachments/files/17157811/gotify.log)

**Comment by jmattheis** [comment]
Have you tried everything listed in here? https://dontkillmyapp.com/xiaomi

Looks like the OS force kills the background process because no "destroy" handlers are executed. I don't think there is much gotify/android can do about this.

**Comment by rikonaka** [comment]
> Have you tried everything listed in here? https://dontkillmyapp.com/xiaomi
> 
> Looks like the OS force kills the background process because no "destroy" handlers are executed. I don't think there is much gotify/android can do about this.

Thank you very much for you reply, its seems is the problem of Xiaomi instead of gofity, thanks again for all the work you all done. ❤️
