### ISSUE TITLE
Lack of notifications

### ISSUE THREAD

**Issue by kisst** [gotify/android#377]
My best guess is that the background notifications depends on Google Play Services ( which I don't have ) as otherwise running a pretty standard setup however I never seen any pop up notification apart from the message saying  "connected" when I open the application and  refresh then messages show up but never pushed  to the device .
I had similar issues with Element but their # F-Droid builds now use simple web sockets rather than play services .
Hence my question is simply is there anything else I might be missing and if not then is there any chance to create a G service independent build variant.

**Comment by jmattheis** [comment]
gotify/android doesn't use googleplay services.

- Do you receive messages on the webui while it's open?
- Are you setting a message priority, without it the message could be hidden -> https://github.com/gotify/android?tab=readme-ov-file#message-priorities
- Could you post logs of the gotify/android app after you've sent a message to gotify/server?

**Comment by kisst** [comment]
priorities where the missing piece , I set the default priority for each application as some doesn't support it and messages started to show up .
I loved gotify even without this too and now it's even better!
Thanks for the help.
