### ISSUE TITLE
Feature Request: Sound Choices

### ISSUE THREAD

**Issue by phoniclynx** [gotify/android#380]
I can't believe no-one has asked for this yet:
I've been looking for some time for an app where I can get different sound notifications for different notifications.

 I want to be able to hear a sound and without taking my phone out of my pocket I want to know how much priority I give to the notification. i.e. HomeAssistant reports that a door has been left open when you leave the house and produces one sound... then Docker says there's an update to a container that reports a different sound. 

It would be handy to be able to set this as an option with the data that is set to gotify. So any app can use the default sound or one can be set through a notification POST command.

**Comment by jmattheis** [comment]
See https://github.com/gotify/android/issues/18#issuecomment-2027980969 and https://github.com/gotify/android/issues/340
