### ISSUE TITLE
Request: Different sound based on priority.

### ISSUE THREAD

**Issue by npelov** [gotify/android#395]
It would  be nice to configure sound based on priority (with option for silence). Some messages are very important - server died, others happen now and then - received contact from a site. If you receive lots of notifications you might miss important ones. Maybe also select different background.

**Comment by jmattheis** [comment]
See https://github.com/gotify/android/issues/18#issuecomment-2027980969 and https://github.com/gotify/android/issues/340

**Comment by npelov** [comment]
hmm. I missed those. I promise I searched before writing...
I can't figure out how separate channels allows me to select different sound per app. Can you help me with that? I'm using android 14 on samsung S23. In the settings->apps->gotify I see only "allow notifications" and "allow sound/vibration"/Silent. There is no way to select sound (at least I can't find it).

**Comment by jmattheis** [comment]
See https://www.sammobile.com/news/samsung-disables-notification-categories-one-ui-6-1/

**Comment by npelov** [comment]
Thank you!
