### ISSUE TITLE
Make message contents richer

### ISSUE THREAD

**Issue by sik0vny** [gotify/android#49]
Would be great to add some rich content to the messages. Preferable html or some markdown. I would like to attach images inside the messages.

BTW: Is there a possibility to send EOL character in the message when using cUrl?

**Comment by jmattheis** [comment]
> Would be great to add some rich content to the messages. Preferable html or some markdown. I would like to attach images inside the messages.

I've created gotify/server#129 for this.

> Is there a possibility to send EOL character in the message when using cUrl?

Yeah, this should be possible with a linebreak.
```bash
$ curl -X POST "gotify.net/message?token=<token>" -F "title=t" -F "message=my message
new line" -F "priority=5"
```
(there is a real linebreak in this example)

**Comment by pm-pm** [comment]
It would be great to have a small Fix-Font to show ASCII tables correctly.
See example/problem below. 
Thanks.
![gotify_fix_font](https://user-images.githubusercontent.com/47995430/53416458-db33d280-39d3-11e9-9151-0d9f611df175.png)

**Comment by sik0vny** [comment]
@pm-pm I hope this will be possible when markdown will be implemented.

**Comment by canDry** [comment]
No 32bit binaries for Linux?  (I have an old home automation server running debian that I'd like install this on)
