### ISSUE TITLE
Unable to connect to server on local network with custom DNS server

### ISSUE THREAD

**Issue by RockyTV** [gotify/android#52]
I have a dnsmasq instance running to achieve some sort of "NAT loopback", so I can access my server (hosted in my home network) with its DDNS address. If I try to connect to my Gotify server using a web browser, it works. When I use the app, it doesn't. I have to switch to LTE/4G to be able to connect to it.

Log:

![](https://i.imgur.com/UuRxYFo.png)

I think this might be a bug with Android itself, as other apps have this exact same issue - handshake succeeds but the following actions just fail.

**Comment by eternal-flame-AD** [comment]
This should work. I have a similar configuration and it works perfectly.

I guess it is somewhat related to DNS cache. Try restarting the app and/or the phone. If it works, it is highly possible to be related to DNS. 

If it still does not work, make sure that the URL you entered in the app is exactly the same as you what you entered in the browser and try if you can connect with the server LAN IP in your home network. If LAN IP works it should be a configuration error on the NAT or dnsmasq side. The most probable error I could guess now is you exposed gotify on a different port on the Internet from which gotify server itself is hosted on. So when you connected back to home network the port number changes and the app fails to connect.

**Comment by RockyTV** [comment]
> I guess it is somewhat related to DNS cache. Try restarting the app and/or the phone. If it works, it is highly possible to be related to DNS.

It didn't work. I have tried restarting both the phone and the app.

> The most probable error I could guess now is you exposed gotify on a different port on the Internet from which gotify server itself is hosted on.

I run it in a docker container which goes through a nginx reverse proxy, also containerized. It works when I connect via browser but it doesn't work when I use the app. In my PC it works flawlessly and I have the same DNS server setup.

**Comment by eternal-flame-AD** [comment]
I think everything looks fine from the information you provided.

If you are experiencing similar issues on other apps, this might be an issue in the OS, or you might misconfigured these services in the same manner.

If you still need help in this issue, feel free to provide more info(eg: dnsmasq configuration, iptables rules, tcpdump during the error, etc.) so we can take a closer look at what might went wrong:)

**Comment by RockyTV** [comment]
[This is my `dnsmasq.conf`](https://hastebin.com/eyiniqufan.shell)

iirc iptables is disabled. Is there an easy way to use tcpdump without being rooted?

**Comment by eternal-flame-AD** [comment]
Dnsmasq looks fine either:( Still no clue where the problem was.

As for packet dump you could intercept these packets on your home gateway(if you use OpenWrt, etc.), or you could use existing tools such as [this one](https://play.google.com/store/apps/details?id=app.greyshirts.sslcapture) to intercept traffic on your phone with the android VPN API.

**Comment by RockyTV** [comment]
Got another log

![](https://my.mixtape.moe/ptuaoa.png)

**Comment by eternal-flame-AD** [comment]
Okay I have to say I am running out of ideas.

Just make sure that the API is exposed at exactly the same URL under WAN and LAN(you can try this by accessing https://my.domain/version via your working browser). If this succeeds but problem still exists, I have to say I don't have a clue now:( Let's assume that this is your device problem, maybe you could test on another device to verify this.

**Comment by RockyTV** [comment]
I have tested in both my phone, a POCO F1 at MIUI 10, Android Pie, and a Moto X 2014 on Lineage 14.1. Same error. Says "connection refused".

Maybe it'd be better if I tried running it via debug, no? It could shed some light on the issue, or help find a solution.

**Comment by eternal-flame-AD** [comment]
"Connection Refused" generally indicates that the port you specified on the URL(443 from I can see on your screenshot) is not open. Is your gotify server exposed on port 443 on your LOCAL network?

**Comment by RockyTV** [comment]
Uh, it isn't. I host it via Docker and it runs on a different port. But it
passes through a reverse proxy which makes it accessible via HTTPS and port
443. There's no issue if I use LTE.

My first thought was that the websockets weren't being proxied by dnsmasq.

**Comment by eternal-flame-AD** [comment]
Okay I think I know what your problem was. I think you misunderstood how dnsmasq works. dnsmasq is not a proxy, it only overrides the name resolution result from your upstream DNS server. So when you are in your local network, gotify server would be not on the same URL(as port 443 to on your gotify server is not open).

As for the reason why browser works, some browsers such as Chrome has aggressive DNS caching so that it might not have accepted the new resolution result from dnsmasq.

To test my theory, I suggest you reboot your phone, connect to your home network, open your browser and go to the gotify URL you specified in the app. If the page fails to load then I think this is the reason.

**Comment by RockyTV** [comment]
It worked on both Chrome and Fennec, page only failed to load when I was
disconnected.

It's weird because in the logs I see a request from my public IP address
while it should from my phone's IP address. For some reason Android is
ignoring the dnsmasq forwarding for apps. It gets more weird when I can
access my server via VLC, but some other apps like Gotify and Bitwarden
have some issues.

**Comment by eternal-flame-AD** [comment]
Never mind. I think the cause of the problem is clear now. To fix the problem I suggest that you epose gotify at the same port at both LAN or WAN.

**Comment by RockyTV** [comment]
Well, using the port Gotify is exposed to works. I am still trying to figure out why Android will simply ignore these custom DNS settings for apps. You said that browsers have aggressive caching but why does it work when I access it via browser, using the reverse proxy address, and not via app?

Once I have time I'll just run the debug app and try to figure it out.

**Comment by eternal-flame-AD** [comment]
As you said, you have already found that the browser is not following the addresses returned by your local dnsmasq resolver. I think this is the only mystery to be resolved now and actually that is unrelated to gotify itself: it is absolutely normal behavior to accept the latest upstream DNS response and attempt to use the obtained address to connect to the server, so I don't think there is anything we can do regarding this issue on the gotify server/client side.

Still, feel free to comment or e-mail if you wanted to analyze and discuss this problem in depth:)

**Comment by eternal-flame-AD** [comment]
@RockyTV It has been 14 days since the last activity of this issue. Has the issue been resolved, or do you have any further questions regarding this issue? Thanks for your feedback.

**Comment by eternal-flame-AD** [comment]
@jmattheis I think this can be closed. The issue is already understood and it does not seem that any action could be taken from our perspective.
