### ISSUE TITLE
Suggestion: Option to mute an app

### ISSUE THREAD

**Issue by johnchristopher** [gotify/android#61]
Some apps have a high number of notifications and others a low number but we don't want to miss those. Muting the chatty app until we can get back to it would be nice.

**Comment by jmattheis** [comment]
With android 8 or higher the priority on the message will be used to determine how intrusive the message should be. What version of android are you using?

**Comment by johnchristopher** [comment]
I am using Android 7.0.

But I am not sold on the idea of using message priority as a mean to reduce interruptions though since levels don't necessarily carry the same meaning across apps. Plus there are some time when an app importance is momentarily reduced (not being on call, testing, etc.) but the message priority won't change according to that context.

**Comment by eternal-flame-AD** [comment]
Should this be a user-wide option(eg: the information of whether an application is muted is synced to the server, and affects all clients), or just applies to a single client(eg: the information for muting is stored on the client device, and does not influence other clients)?

From your issue description I guess it should be a client-wide option. I just wanted to confirm this. If that is the case I agree that the feature to be added. It resolves problems (I am sometimes annoyed by chatty apps too) and is relatively cheap to implement. If you want a user-wide configuration, it would be not so easy to implement and involves API definition changes.

**Comment by johnchristopher** [comment]
I believe it makes more sense for this feature to be implemented as a client-wide option. Beside, different clients beg different usage and different priorities (that's another context).

**Comment by abeulich** [comment]
I accidentally created a duplicate feature request: [https://github.com/gotify/android/issues/151](https://github.com/gotify/android/issues/151)

So +1 for a way to mute specific apps in a client (for me mostly the Android client, 
since I'm generating gotify push messages from Android notifications there).

**Comment by jmattheis** [comment]
@abeulich I'd be happy to accept a pull request for this feature :P.

**Comment by jmattheis** [comment]
With the new setting introduced in  https://github.com/gotify/android/pull/278 it should be possible to mute a specific application in the android notification settings if "Separate app notification channels" is ienabled in the settings.
