### ISSUE TITLE
Clear notification dot and notification bar automatically by app start

### ISSUE THREAD

**Issue by pm-pm** [gotify/android#62]
When a gotify message was receive during my absence and i wake up the phone i see on the **my** first/home screen the gotify icon with a blue notification dot. (Android 8) That is expected behaviour.

When i start the app, read the message, clear the message and exit the app the notification dot is not removed from app icon beacause the notification is still in the notification bar. I have to clear the notification bar manually too.

Is it possible after starting the app and reading the messsages to clear the notification bar and dot automatically?

**Comment by jmattheis** [comment]
Yeah, that should be possible.

**Comment by pm-pm** [comment]
Hello.
Because this app is currently being worked on, maybe this issue could be solved as well? ;-)

Thanks.

**Comment by jmattheis** [comment]
Hey @pm-pm,

I don't know, if this is the wanted behavior, with https://github.com/gotify/android/pull/91 notifications can have actions like opening a url. When the notifications are cleaned, then it wouldn't be possible to click them. @mzoeller you've implemented the pr, what do you think about this issue?

**Comment by pm-pm** [comment]
Hello jmattheis,
this is a different issue.

When a message is received you see the "notification dot" and an icon in the notification bar. Ok.
Now you open the app by using the "normal app icon" on your home screen. (I have it there)
You read the messages and exit the app.
What do you see? You still see the "notification dot" and the icon in the notification bar. :-/
To remove the "notification dot" now you must ADDITIONALLY remove the notification in the bar manually.

My wish is: To clear "notification dot" and icon in the notification bar when you have read the message by starting the app via "app icon".

Polite: Is is now more clear? :-)

**Comment by mzoeller** [comment]
So the idea is: whenever you clear one (or multiple) messages inside the Gotify app, the corresponding Android notifications are removed as well. Correct?

**Comment by pm-pm** [comment]
No really. ;-)
Clearing/deleting a message is not necessary.

If you **open** the app (tap on gotify icon on home screeen) and just **view** the new messages and exit the app, then clear the dot and notification icon.

**Comment by mzoeller** [comment]
Check. I've submitted a pull request: https://github.com/gotify/android/pull/93

As for the url click feature. Maybe a nice way to handle it would be to add a clickable link to each message inside the Gotify app?

**Comment by pm-pm** [comment]
Works perfektly with 2.0.11.

Thanks a lot. :-)
