### ISSUE TITLE
v2.0.6: How make a carriage return in messages now?

### ISSUE THREAD

**Issue by pm-pm** [gotify/android#65]
From client version 2.0.6 the "\n" is ignored and the send text messages and displayed as single line.
Is that due to the markdown implementation?
What is now the right character in the textmessage to have a carriage return?

**Comment by eternal-flame-AD** [comment]
In markdown, you need two returns to render as a new line.

**Comment by pm-pm** [comment]
But it does not work correctly.

_Android Version 2.0.5 (werks well)_
Server sends: "**TestLineOne\nTestLineTwo**" (One \n)
On telephone:
```
TestLineOne
TestLineTwo
```

_Android Version 2.0.6_
Server sends: "**TestLineOne\nTestLineTwo**" (only one \n)
Makes NO Carriare Return :-(
On telephone:
`TestLineOneTestLineTwo`


Server sends: "**TestLineOne\n\nTestLineTwo**" (with two \n)
Makes TWO Carriage Return. (One additional space line) :-(
On telephone:
```
TestLineOne

TestLineTwo
```

Could you please check this. :-)

**Comment by eternal-flame-AD** [comment]
Seems that the WebUI renderer and android renderer behaves differently, I tried some techniques and I think this one works.

https://spec.commonmark.org/0.28/#example-605

**Comment by pm-pm** [comment]
Sorry, but this does also not work. What do i do wrong?
Using "<br /> has not effect in android app (everything in one line) and in web ui the string "<br />" is visible.

**Comment by eternal-flame-AD** [comment]
Maybe you did not send the message correctly(not escaping some characters, etc.) This is how I tested this solution.
```bash
curl -X POST "https://example.com/message?token=AXXXXXX&message=Hello  %0AWorld"
```
![image](https://user-images.githubusercontent.com/35571479/55290483-6b679c00-5406-11e9-9ee5-3f6d91f59fa6.png)

**Comment by pm-pm** [comment]
I am not so happy, but i have found some working ways. Maybe you can add them to documentation.
Here the solution with "curl"
```
# curl -X POST "https://gotify.example.com/app/message?token=Axxxxxxxxxxxxxx&message=Hello%0AWorld"
{"id":5093,"appid":8,"message":"Hello\nWorld","title":"www","priority":0,"date":"2019..."}
```
![ghhw1](https://user-images.githubusercontent.com/47995430/55484114-33d83a00-5628-11e9-8ad3-572ed76a2709.png)


```
# curl -X POST "https://gotify.example.com/app/message?token=Axxxxxxxxxxxxxx&message=Hello  %0AWorld"
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>
```
No Message on phone.

```
# curl -X POST "https://gotify.example.com/app/message?token=Axxxxxxxxxxxxxx&message=Hello%20%20%0AWorld"
{"id":5094,"appid":8,"message":"Hello  \nWorld","title":"www","priority":0,"date":"2019..."}
```
![ghhw2](https://user-images.githubusercontent.com/47995430/55484139-405c9280-5628-11e9-866d-27b4c429d00a.png)

With curl only this works as espected.

**Comment by eternal-flame-AD** [comment]
Okay, seems that nginx is rejecting spaces in the URL, but an unescaped space character is acceptable with a bare gotify instance.

@jmattheis Do you think this should be included in the documentation?

**Comment by pm-pm** [comment]
Here my solution with the gotify command line client on debian 9 and bash.
This line is also useable in bash scripts.

`printf -v CR "  \n" ; ./gotify-cli-linux-amd64 p -p 0 --url "https://gotify.example.com/app" --token "Axxxxxxxxxxxxxx" "TestLineOne${CR}TestLineTwo"`

![ghhw3](https://user-images.githubusercontent.com/47995430/55484663-338c6e80-5629-11e9-977b-658c8f3eff4d.png)

All other "combination" in the printf command do not work (for me).

**Comment by pm-pm** [comment]
I am using as "target" the apache webserver with reverse proxy setup. (I added (edit) this information to my examples)

**Comment by eternal-flame-AD** [comment]
Yeah, eventually we need to make gotify receive a message that is in the format "First Line..\nSecond line".

If we send the message URL through query binding, the best practice would be to URL encode both the space and the return, but it won't be a problem when sending the request in json format.

**Comment by ceptonit** [comment]
I have the same issue posting in python:
```
import requests as req

push_gotify = req.post('https://gotify.example.com/message?token=xxxxxxxxxx',
                           json={"message": "Line1\nLine2", "title": "Test Title"})
```
gives me: 
`Line1 Line2`

'\n' seems to be replaced by a whitespace instead of a new line.

Now, if I put 2 new lines in a row like '\n\n' I actually get an extra line.
```
import requests as req

push_gotify = req.post('https://gotify.example.com/message?token=xxxxxxxxxx',
                           json={"message": "Line1\n\nLine2", "title": "Test Title"})
```
gives me:
```
Line 1

Line 2
```

**Comment by eternal-flame-AD** [comment]
@ceptonit Try this one:
```python
import requests as req

push_gotify = req.post('https://gotify.example.com/message?token=xxxxxxxxxx',
                           json={"message": "Line1  \nLine2", "title": "Test Title"})
```

**Comment by ceptonit** [comment]
@eternal-flame-AD Yep that did the trick, thanks ;)

**Comment by jmattheis** [comment]
With #67 the default for messages is again plaintext.
