### ISSUE TITLE
gotify app gets killed

### ISSUE THREAD

**Issue by djwlindenaar** [gotify/android#68]
I'm running 2.0.6 on my android phone and for some reason gotify dies at some point and does not restart. This does not happen to e.g. Whatsapp nor Facebook. 

Anything I should configure or can I provide more information to figure out what is happening?

Best regards
Daniel

**Comment by jmattheis** [comment]
Did you disable battery optimization? See https://github.com/gotify/android#disable-battery-optimization

**Comment by djwlindenaar** [comment]
argh, missed that hint ... in the readme ... on the front page ... sorry about that. I will test it this way.

However, I note that apps like Whatsapp do not have this optimization disabled in the settings. Do they use some kind of permission or so to disable is programattically?

**Comment by jmattheis** [comment]
These services use FCM (fire cloud messaging) from google for managing notifications, gotify does not use any third party services and therefore uses different means to have similar functionally, sadly this needs a android background service that is always running.

**Comment by djwlindenaar** [comment]
Right, could have known something like this was behind in. And that's the whole reason I wanted to use gotify. 

Thanks for clearing this up and sorry for the RTFM question.
