### ISSUE TITLE
Markdown Inline-style images not rendering

### ISSUE THREAD

**Issue by ceptonit** [gotify/android#69]
> gotify/android v2.0.6
> gotify/server v2.0.4

Sending an Inline-style image using Markdown doesn't render the image on the android app but does correctly on the server app.

`![alt text](https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png)`

Sending the above message results in only getting "alt text" on android.

**Comment by jamesawebb** [comment]
For anyone else wondering, I'm still seeing this on:
gotify/sever v2.1.4
gotify/android 2.3.3
I am new to gotify - high chance I'm doing something wrong.

**Comment by ceptonit** [comment]
> For anyone else wondering, I'm still seeing this on: gotify/sever v2.1.4 gotify/android 2.3.3 I am new to gotify - high chance I'm doing something wrong.

You are doing something wrong indeed.
By default, gotify sends in "text/plain" format.
To send in the markdown format, you have to explicitly indicate it for each message using the "extras" settings.
Here's what you can set using Extras: https://gotify.net/docs/msgextras
Here's an example on how to send a markdown message with Bash: https://gotify.net/docs/more-pushmsg

**Comment by jamesawebb** [comment]
Yup - one night later and I have markdown working - as well as inline images, Android intent handling etc.  Ashamedly I can't quite recall what I had done wrong.
I *knew* this was a premature posting :P
