### ISSUE TITLE
button for share/push to the server application

### ISSUE THREAD

**Issue by anibal-aguila** [gotify/android#72]
Hi, I found this plugin for share from chrome to the server app but the android app doesn't have the button for share/push to the server apps.

https://github.com/mskian/gotify-push/

![image](https://user-images.githubusercontent.com/49025536/58371508-0b770880-7f12-11e9-8a76-5c28789b99ef.png)

thanks in advance,

**Comment by jmattheis** [comment]
We once had a pr for this, sadly it wasn't finished. https://github.com/gotify/android/pull/53 but yeah, it would be a good feature.

**Comment by 4oo4** [comment]
@jmattheis How much progress was made on it, and what is missing?

**Comment by jmattheis** [comment]
Well, it works, but it is not configurable which application should be used for sending the message and what priority the message should have. For these settings are new settings page is needed.
So the biggest point would be the settings page I guess.

**Comment by kmahyyg** [comment]
I just checked the src in repo, seems the API endpoint and request details are already prepared. Seems we just need an UI for it? maybe a new page in side panel called "send a noti", then just let user choose the application from list and set the title,message,priority themselves, then we just post it out. Seems fine?

**Comment by jmattheis** [comment]
I think the main point is that the app interacts with the android share system. With this it would be possible to share information without opening the gotify app and manually pasting stuff. 
An additional page would still be useful I guess.

**Comment by kmahyyg** [comment]
> I think the main point is that the app interacts with the android share system. With this it would be possible to share information without opening the gotify app and manually pasting stuff.
> An additional page would still be useful I guess.

Thanks for your reply. If we need to build share system, we might need to create a share shortcut for each application inside our app and define a default title,priority and just let user-defined content to be the push message body. It's really hard. 

Thanks again for your brilliant work.

**Comment by jmattheis** [comment]
Maybe when sharing we open an activity to let the user choose the application and priority if that's possible.

**Comment by kmahyyg** [comment]
Totally possible, what we need is just a pop-up.

**Comment by dvtkrlbs** [comment]
Is there any progress on this? This feature would make me completely ditch pushbullet.

**Comment by jmattheis** [comment]
@dvtkrlbs, no but feel free to implement it (:.

**Comment by tomasvanagas** [comment]
Hey guys, I'm working on it :)
https://github.com/tomasvanagas/android

**Comment by jmattheis** [comment]
Added in #122
