### ISSUE TITLE
Please add/allow markdown/links also in "Title"

### ISSUE THREAD

**Issue by pm-pm** [gotify/android#73]
Hello,
could you please add or allow to use links also in the **Title**. In Textarea it is not suitable.
Here my example:

> **Trainstation: Paris**
> Information Train 111 : Delay +100
> Information Train 222 : On Time
> Information Train 333 : Cancelled

Where to add the link to the train station Paris? ;-) - In the Tiltle

Many Thanks.

**Comment by jmattheis** [comment]
We could add such functionality via [message extras](https://gotify.net/docs/msgextras). However, I think it would be better to add the link in the message instead, much easier than adding this feature.

**Comment by jmattheis** [comment]
Closing as not needed as there aren't many upvotes or comments from other users.
