### ISSUE TITLE
It looks like usefull, Who want use this?

### ISSUE THREAD

**Issue by jhzao82** [gotify/android#76]
I dont know about this app do? Can you give me some advices?

**Comment by jmattheis** [comment]
Hey @jhzao82,
this app can connect to a running instance of [gotify/server](https://github.com/gotify/server). This server provides a REST-API to publish messages. For each new message the gotify/android app will create a push notification. 

Gotify does all of this without using any third-party services like Firebase Cloud Messaging (Googles service for notifications), thus enabling you to have full control over your data.

You can use Gotify for all kind of things that you want to get notified for. Like SSH-Logins, server reboots or website deployments.

**Comment by jhzao82** [comment]
I cant imageine It works in action, How do find some real project doing this?

**Comment by jmattheis** [comment]
What do you mean with real projects? You can send messages in simple bash scripts, so you shouldn't need any other projects. Gotify is integrated in some services like Radarr or Sonarr but I think it is mostly used in short scripts.

**Comment by jhzao82** [comment]
If you send message at server, and login to app you can get this message?

**Comment by eternal-flame-AD** [comment]
Yes, it connects to the server and notifies you about the messages posted to the server with a notification.

**Comment by jhzao82** [comment]
Thank you! If I can get try in local, If I dont have internet server?

**Comment by eternal-flame-AD** [comment]
It works as long as you can connect to the server you hosted, it doesn't matter if it is exposed on the Internet or only on your local network.

**Comment by jhzao82** [comment]
OK, I will try later, Thank you!

**Comment by eternal-flame-AD** [comment]
Hope to see you get everything goes up and running :) Feel free to ask our community on Riot.im or GitHub issue for further questions.
