### ISSUE TITLE
App does not notify (no sound/no point) after about 1 week.

### ISSUE THREAD

**Issue by pm-pm** [gotify/android#78]
Hello,

our smartphones (Moto 5 Android 8.1) normally work 24h a day without reboot. 
After about 1 week (without touching the app?) the gotify app does not notify for new messages. (No sound/No Point)
At this point you can send as many messages, but not notified by app.
If you open the app, you see all the messages.
BUT also the next message is not notified.
**This means: After a while the app loses the ability to notify about new messages no matter if you open the app or not.**

You can only solve the problem if you stop the app manually in settings and start it again.
From this point all new messages are notified with sound and point.

This happens on both phones. Has anybody an idea what the problem is?
Could someone verify this?

Thanks.

pm-pm

**Comment by eternal-flame-AD** [comment]
Is the gotify background service still running? (Check for the persistent notification on your notification panel)

**Comment by pm-pm** [comment]
Ok. I had disabled the icon in settings. (Gotify foreground notification = off)

The problem is: When "Gotify foreground notification = on" and you receive a message you have two icons in notification panel.

Now i have switch it on and will watch it.

Thank. :-)

**Comment by eternal-flame-AD** [comment]
Which android version are you using? I believe that from Android O you can collapse persistent notifications.

**Comment by pm-pm** [comment]
Motorola G5 with Android 8.1

**Comment by eternal-flame-AD** [comment]
Try long press on the persistent notification and then press "hide".

**Comment by pm-pm** [comment]
I think that is exactly the same point (same setting/item) as using the app configuration/notification dialog.

So i will wait for some time and watch what happens. :-)

Thanks.
