### ISSUE TITLE
Markdown is entirely re-rendered as you're scrolling up and down, resulting in images redownloading

### ISSUE THREAD

**Issue by beerendlauwers** [gotify/android#79]
**Issue:** After pushing a few Markdown-formatted messages with images in them, older messages are pushed downwards. After a message is out of the view bounds, it seems to be "forgotten" about: scrolling back to a message you previously viewed re-renders the message and downloads the image all over again.

**Suggestion:** Cache images in notifications on the device. As soon as a notification is deleted, any accompanying images for that notification are removed from the cache.

**Comment by jmattheis** [comment]
With https://github.com/gotify/android/commit/d9113a8a959a7b66bba75fbdb12d27b9cd1cf883 images will be cached between rerenders.

Full caching could be integrated via https://github.com/gotify/android/issues/58 or https://github.com/gotify/android/issues/86 so I'm closing this issue.

**Comment by beerendlauwers** [comment]
Just tested it, works stellar!
