### ISSUE TITLE
Directly copy & share from notification bar

### ISSUE THREAD

**Issue by emdoe** [gotify/android#80]
It would be more convenient if gotify provides two buttons (copy and share the contents) in the notification bar (under the pushing message, just like "mark as read" and "reply" for IM apps). Correspondingly, a useful option could be that the click of one of these buttons will also automatically clear the notification. However, the hard problem for this feature could be concluded as “what to copy” since I think many users wouldn’t like to share the text organized by markdown. However, copying entire message in plain text will omit the images as well as saving the message as a html file would not be handy for most users. IMO a possible solution could be providing users two options including share and open (see my comment below). If the message just contains a link of one image, (saves and) shares this image. Otherwise shares plain text. Besides, when users click the notification and open the gotify app, provides them an option (e.g., long press the message) to export whole text as markdown or plaintext to the storage.

Besides, it would be great if the app allows users to choose the copy whether or not including the title.

Thanks for consideration.

**Comment by emdoe** [comment]
https://github.com/gotify/server/issues/119

**Comment by jmattheis** [comment]
Closing as not needed as there aren't many upvotes or comments from other users.

**Comment by athulpa** [comment]
This would be neat feature to have. There are so many possibilities, but let me share my experience.

My Use Case:
I'm using gotify CLI (wrapped wiithin a bash alias 'gclip') as a clipboard tool that sends text over to my phone
As a homelabber, copying pieces of code/output to my phone to then share it elsewhere is a regular use case.
I have attached the bash function for reference, you may try it out.
[gclip.sh](https://github.com/user-attachments/files/31230642/gclip.sh)

Painpoint:
The script works brilliantly to send the text, but at present it's clunky to copy the text once it arrives on the phone itself.
I have to click on the notification to open the app, then long press to select the message as shown there.

Proposed solution:
Best for me would be a simple "copy text" button. It would omit the title and copy the plain text of the message only.
