### ISSUE TITLE
WebSocket: failure StatusCode: 400 Message

### ISSUE THREAD

**Issue by fancypantalons** [gotify/android#82]
I'm seeing constant errors of this form (see subject) in the app logs on the device.  The stack trace in the log doesn't look too terribly useful, but I can supply it if it's helpful.

Meanwhile, the Gotify persistent connection notification shows "Could not connected Bad Request", which is obviously the result of this error.

Attaching to the server console, I'm seeing instances of this error, which I suspect is related:

Error #01: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header

For reference, this is using the latest docker server image and the latest version of the app published on the Play store on a Pixel 3 running Android Q.

Ultimately, I'm seeing no push notifications on the device, and I can only assume this is related (my guess is the websocket exception is thrown before the notification can be published, but I haven't looked at the code so that really is wild speculation).

Let me know if there's any other information I can supply that might help diagnose this issue!

**Comment by eternal-flame-AD** [comment]
Do you have any reverse proxies in front of the server?

**Comment by fancypantalons** [comment]
Gah.  I absolutely do, yes!  And of course that could be causing a problem... I'll dig around for any references to reverse proxying with Apache and websocket services.  Thanks for pointing me in the right direction!

**Comment by jmattheis** [comment]
@fancypantalons We have documentation about it (:. https://gotify.net/docs/apache

**Comment by fancypantalons** [comment]
🤦‍♂ 

Thanks.  LOL

**Comment by fancypantalons** [comment]
BTW, for anyone who searches for this issue in the tracker and runs across it: unsurprisingly, the documents worked perfectly (and are very clear... nicely done!) and I'm now happily receiving notifications on my phone.  So... yeah... amazing what happens when you RTFM...
