### ISSUE TITLE
Application killed on connection issue

### ISSUE THREAD

**Issue by Leosirth** [gotify/android#83]
Hi,

I notice that from time to time the application just get killed and I need to reopen it.
Today morning when this happened I can see the following in the logs (ordered from most recent):

```
WARN: Destroy WebSocketService
INFO: WebSocket: closing existing connection
INFO: WebSocket: Network not connected
ERROR: WebSocket: failure Message: java.net.SocketTimeoutException: failed to connect to *** after 10000ms
...
```

Is this an expected behaviour?
Can a retry be implemented instead to close the app?

Thanks and regards,

**Comment by jmattheis** [comment]
Normally it should automatically reconnect. Which android version do you have, do you use a vpn to connect to the network? Could you try to start the app then manually disconnect mobile/wifi network, then reenable it and check if gotify does reconnect?

**Comment by pm-pm** [comment]
Hello,
what is "time to time"? ;-)
Could this be the same problem as mine? #78

**Comment by Leosirth** [comment]
@jmattheis I don't use a VPN, going to airplane made turn the app to "waiting for network", I think the issue occur on socket timeout. Android version is 9

@pm-pm Can't say how often, maybe 1 or 2 times per week. Seems different from your behaviour.

**Comment by jmattheis** [comment]
Have you [disabled battery optimization](https://github.com/gotify/android#disable-battery-optimization)?

**Comment by Leosirth** [comment]
@jmattheis I have the fixed notification to prevent the app to be killed, have now also disabled the battery optimization, but this will only limit the background activity isn't it?

Will let you know if this will happen again.

Thanks and regards,

**Comment by jmattheis** [comment]
The foreground notification doesn't prevent the app to be killed, it just makes it less likely :D
