### ISSUE TITLE
gotify android not pushing notification to server

### ISSUE THREAD

**Issue by JunkyardCat** [gotify/android#84]
my server is 2.0.10
my app is 2.0.7
android ver is 6.0.1

i installed the app
logged in 
http://XXX.XXX.X.XXX:XX
username:admin
password:admin

web logged in as admin

after someone texted me the android OS is now showing 1 message received. I checked gotify and cant find any trace of a message. I then checked the server which i access on a windows web browser firefox, still no message

**Comment by jmattheis** [comment]
Hi @JunkyardCat,

What exactly do you mean with `someone texted me the android OS`? 

Have you sent a message like described in here https://gotify.net/docs/pushmsg?

**Comment by JunkyardCat** [comment]
Hi @jmattheis 
Im really new to this and dont really know what to do to make it send message to the server. what apps do i need?

**Comment by jmattheis** [comment]
Yeah, our android app can only receive messages. There are some third-party android apps which enable you to send messages.

**Comment by pm-pm** [comment]
>There are some third-party android apps which enable you to send messages.

*thinking-very-long*
Which apps can do this? :-) Do you have a name?

Btw: From my point the gotify app should not send any messages. The way of working is ok.
