### ISSUE TITLE
No notifications until I open the app by hand

### ISSUE THREAD

**Issue by chrisiaut** [gotify/android#89]
Hello, I just set up my gotify server and installed the app and if I push a message (eg from the cli tool)
I get the notification on my desktop but on Android I don't get it until I open the app. Actually not even then I just see the pushed messages in the app but get no further notification at all.

**Things I've checked:**

- [x] The app has all checkmarks set in the Android notification settings and other apps like whatsapp, gmail and amazon are sending notifications just right.
- [x] Background service is running
- [x] It's in the notification bar with "Listening to..."
- [x] No battery saving settings set for the app
- [x] Same from wifi or celluar network
- [x] No change after restart

**More info:**

- gotify/android v2.0.9
- gotify/server v2.0.12
- Phone: One Plus 3T
- Build A3003_28_191104
- Android 9 (10.19)
- Kernel 3.18

**Comment by chrisiaut** [comment]
Interesting. If I'm setting a priority higher than 0 (default) I get the notification 

`gotify push -t "my title" -p 10 "Hello World"`

**Comment by jmattheis** [comment]
FYI: It's defined here https://github.com/gotify/android#message-priorities
